import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'ko',
        'en',
        'ja',
        'zh_Hans',
        'zh_Hant',
        'it',
        'fr',
        'de',
        'nl',
        'es',
        'ar',
        'vi',
        'ta',
        'th',
        'tr',
        'uk',
        'id',
        'ms',
        'pl',
        'pt',
        'sv',
        'da',
        'hu',
        'el',
        'he',
        'hi',
        'lv',
        'ne',
        'mn',
        'uz',
        'sl',
        'ro',
        'ml',
        'no',
        'ru',
        'sk',
        'fa',
        'af',
        'az',
        'am',
        'eu',
        'be',
        'bn',
        'my',
        'bs',
        'bg',
        'km',
        'sq',
        'cs',
        'hr',
        'et',
        'hy',
        'fi',
        'ka',
        'gu',
        'is',
        'gl',
        'kn',
        'kk',
        'lo',
        'mk',
        'mr',
        'lt',
        'ca',
        'or',
        'pa',
        'ps',
        'sr',
        'sm',
        'si',
        'sw',
        'te',
        'sd',
        'tl',
        'ur',
        'ky',
        'zu'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? koText = '',
    String? enText = '',
    String? jaText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? itText = '',
    String? frText = '',
    String? deText = '',
    String? nlText = '',
    String? esText = '',
    String? arText = '',
    String? viText = '',
    String? taText = '',
    String? thText = '',
    String? trText = '',
    String? ukText = '',
    String? idText = '',
    String? msText = '',
    String? plText = '',
    String? ptText = '',
    String? svText = '',
    String? daText = '',
    String? huText = '',
    String? elText = '',
    String? heText = '',
    String? hiText = '',
    String? lvText = '',
    String? neText = '',
    String? mnText = '',
    String? uzText = '',
    String? slText = '',
    String? roText = '',
    String? mlText = '',
    String? noText = '',
    String? ruText = '',
    String? skText = '',
    String? faText = '',
    String? afText = '',
    String? azText = '',
    String? amText = '',
    String? euText = '',
    String? beText = '',
    String? bnText = '',
    String? myText = '',
    String? bsText = '',
    String? bgText = '',
    String? kmText = '',
    String? sqText = '',
    String? csText = '',
    String? hrText = '',
    String? etText = '',
    String? hyText = '',
    String? fiText = '',
    String? kaText = '',
    String? guText = '',
    String? isText = '',
    String? glText = '',
    String? knText = '',
    String? kkText = '',
    String? loText = '',
    String? mkText = '',
    String? mrText = '',
    String? ltText = '',
    String? caText = '',
    String? orText = '',
    String? paText = '',
    String? psText = '',
    String? srText = '',
    String? smText = '',
    String? siText = '',
    String? swText = '',
    String? teText = '',
    String? sdText = '',
    String? tlText = '',
    String? urText = '',
    String? kyText = '',
    String? zuText = '',
  }) =>
      [
        koText,
        enText,
        jaText,
        zh_HansText,
        zh_HantText,
        itText,
        frText,
        deText,
        nlText,
        esText,
        arText,
        viText,
        taText,
        thText,
        trText,
        ukText,
        idText,
        msText,
        plText,
        ptText,
        svText,
        daText,
        huText,
        elText,
        heText,
        hiText,
        lvText,
        neText,
        mnText,
        uzText,
        slText,
        roText,
        mlText,
        noText,
        ruText,
        skText,
        faText,
        afText,
        azText,
        amText,
        euText,
        beText,
        bnText,
        myText,
        bsText,
        bgText,
        kmText,
        sqText,
        csText,
        hrText,
        etText,
        hyText,
        fiText,
        kaText,
        guText,
        isText,
        glText,
        knText,
        kkText,
        loText,
        mkText,
        mrText,
        ltText,
        caText,
        orText,
        paText,
        psText,
        srText,
        smText,
        siText,
        swText,
        teText,
        sdText,
        tlText,
        urText,
        kyText,
        zuText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'c0ob4q61': {
      'ko': '꺼짐',
      'af': 'Af',
      'am': 'ጠፍቷል',
      'ar': 'عن',
      'az': 'Söndür',
      'be': 'Выключана',
      'bg': 'Изключено',
      'bn': 'বন্ধ',
      'bs': 'Isključeno',
      'ca': 'Desactivat',
      'cs': 'Vypnuto',
      'da': 'Slukket',
      'de': 'Aus',
      'el': 'Μακριά από',
      'en': 'Off',
      'es': 'Apagado',
      'et': 'Väljas',
      'eu': 'Itzalita',
      'fa': 'خاموش',
      'fi': 'Pois',
      'fr': 'Désactivé',
      'gl': 'Desactivado',
      'gu': 'બંધ',
      'he': 'כבוי',
      'hi': 'बंद',
      'hr': 'Isključeno',
      'hu': 'Le',
      'hy': 'Անջատված',
      'id': 'Mati',
      'is': 'Slökkt',
      'it': 'Spento',
      'ja': 'オフ',
      'ka': 'გამორთულია',
      'kk': 'Өшірулі',
      'km': 'បិទ',
      'kn': 'ಆಫ್',
      'ky': 'Өчүк',
      'lo': 'ປິດ',
      'lt': 'Išjungta',
      'lv': 'Izslēgts',
      'mk': 'Исклучено',
      'ml': 'ഓഫ്',
      'mn': 'Унтраах',
      'mr': 'बंद',
      'ms': 'Mati',
      'my': 'ပိတ်သည်။',
      'ne': 'बन्द',
      'nl': 'Uit',
      'no': 'Av',
      'or': 'ବନ୍ଦ ଅଛି',
      'pa': 'ਬੰਦ',
      'pl': 'Wyłączony',
      'ps': 'بند',
      'pt': 'Desligado',
      'ro': 'Dezactivat',
      'ru': 'Выключенный',
      'sd': 'بند',
      'si': 'අක්‍රියයි',
      'sk': 'Vypnuté',
      'sl': 'Izklopljeno',
      'sm': 'Tape',
      'sq': 'Joaktiv',
      'sr': 'Искључено',
      'sv': 'Av',
      'sw': 'Imezimwa',
      'ta': 'ஆஃப்',
      'te': 'ఆఫ్',
      'th': 'ปิด',
      'tl': 'Naka-off',
      'tr': 'Kapalı',
      'uk': 'Вимкнено',
      'ur': 'آف',
      'uz': 'Oʻchirilgan',
      'vi': 'Tắt',
      'zh_Hans': '离开',
      'zh_Hant': '離開',
      'zu': 'Valiwe',
    },
    '24qab3qx': {
      'ko': '켜짐',
      'af': 'Aan',
      'am': 'በርቷል',
      'ar': 'على',
      'az': 'Aktiv',
      'be': 'Уключана',
      'bg': 'Включено',
      'bn': 'চালু',
      'bs': 'Uključeno',
      'ca': 'Activat',
      'cs': 'Na',
      'da': 'På',
      'de': 'An',
      'el': 'Επί',
      'en': 'On',
      'es': 'En',
      'et': 'Sees',
      'eu': 'Piztuta',
      'fa': 'روشن',
      'fi': 'Päällä',
      'fr': 'Sur',
      'gl': 'Activado',
      'gu': 'ચાલુ',
      'he': 'עַל',
      'hi': 'पर',
      'hr': 'Na',
      'hu': 'On',
      'hy': 'Միացված է',
      'id': 'Pada',
      'is': 'Kveikt',
      'it': 'SU',
      'ja': '点灯',
      'ka': 'ჩართულია',
      'kk': 'Қосулы',
      'km': 'បើក',
      'kn': 'ಆನ್',
      'ky': 'Күйүк',
      'lo': 'ສຸດ',
      'lt': 'Įjungta',
      'lv': 'Ieslēgts',
      'mk': 'Вклучено',
      'ml': 'ഓൺ',
      'mn': 'Асаалттай',
      'mr': 'चालू',
      'ms': 'hidup',
      'my': 'ဂရန်',
      'ne': 'खुल्ला',
      'nl': 'Op',
      'no': 'På',
      'or': 'ଅନ୍',
      'pa': 'ਚਾਲੂ',
      'pl': 'NA',
      'ps': 'په',
      'pt': 'Sobre',
      'ro': 'Pe',
      'ru': 'На',
      'sd': 'تي',
      'si': 'ක්‍රියාත්මකයි',
      'sk': 'Zapnuté',
      'sl': 'Vklopljeno',
      'sm': 'luga',
      'sq': 'Aktiv',
      'sr': 'Укључено',
      'sv': 'På',
      'sw': 'Washa',
      'ta': 'அன்று',
      'te': 'ఆన్',
      'th': 'บน',
      'tl': 'Naka-on',
      'tr': 'Açık',
      'uk': 'Увімкнено',
      'ur': 'پر',
      'uz': 'Yoniq',
      'vi': 'TRÊN',
      'zh_Hans': '在',
      'zh_Hant': '在',
      'zu': 'Vuliwe',
    },
    'iq5z1i00': {
      'ko': '손전등',
      'af': 'Flitslig',
      'am': 'የእጅ ባትሪ',
      'ar': 'مصباح يدوي',
      'az': 'Fənər',
      'be': 'Ліхтарык',
      'bg': 'Фенерче',
      'bn': 'টর্চলাইট',
      'bs': 'Svjetiljka',
      'ca': 'Llanterna',
      'cs': 'Svítilna',
      'da': 'Lommelygte',
      'de': 'Taschenlampe',
      'el': 'Φακός',
      'en': 'Flashlight',
      'es': 'Flash',
      'et': 'Taskulamp',
      'eu': 'Linterna',
      'fa': 'چراغ قوه',
      'fi': 'Taskulamppu',
      'fr': 'Lampe de poche',
      'gl': 'Lanterna',
      'gu': 'ફ્લેશલાઇટ',
      'he': 'פָּנַס כִּיס',
      'hi': 'टॉर्च',
      'hr': 'Svjetiljka',
      'hu': 'Zseblámpa',
      'hy': 'Լապտեր',
      'id': 'Senter',
      'is': 'Vasaljós',
      'it': 'Torcia elettrica',
      'ja': '懐中電灯',
      'ka': 'ფანარი',
      'kk': 'Фонар',
      'km': 'ពិល',
      'kn': 'ಫ್ಲ್ಯಾಶ್‌ಲೈಟ್',
      'ky': 'Кол чырак',
      'lo': 'ໄຟສາຍ',
      'lt': 'Žibintuvėlis',
      'lv': 'Lukturītis',
      'mk': 'Фенерче',
      'ml': 'ഫ്ലാഷ്‌ലൈറ്റ്',
      'mn': 'Гар чийдэн',
      'mr': 'टॉर्च',
      'ms': 'Lampu suluh',
      'my': 'ဓာတ်မီး',
      'ne': 'टर्चलाइट',
      'nl': 'Zaklamp',
      'no': 'Lommelykt',
      'or': 'ଫ୍ଲାସଲାଇଟ୍',
      'pa': 'ਫਲੈਸ਼ਲਾਈਟ',
      'pl': 'Flesz',
      'ps': 'لاسي څراغ',
      'pt': 'Lanterna',
      'ro': 'Lanternă',
      'ru': 'Фонарик',
      'sd': 'ٽارچ',
      'si': 'ෆ්ලෑෂ් ලයිට්',
      'sk': 'Baterka',
      'sl': 'Svetilka',
      'sm': 'moliuila',
      'sq': 'Fener',
      'sr': 'Батеријска лампа',
      'sv': 'Ficklampa',
      'sw': 'Tochi',
      'ta': 'பிரகாச ஒளி',
      'te': 'ఫ్లాష్‌లైట్',
      'th': 'ไฟฉาย',
      'tl': 'Flashlight',
      'tr': 'El feneri',
      'uk': 'Ліхтарик',
      'ur': 'ٹارچ',
      'uz': 'Chiroq',
      'vi': 'Đèn pin',
      'zh_Hans': '手电筒',
      'zh_Hant': '手電筒',
      'zu': 'Ithoshi',
    },
    'pumtmx3a': {
      'ko': '홈',
      'af': 'huis',
      'am': 'ቤት',
      'ar': 'بيت',
      'az': 'ev',
      'be': 'дом',
      'bg': 'дом',
      'bn': 'বাড়ি',
      'bs': 'dom',
      'ca': 'casa',
      'cs': 'domov',
      'da': 'hjem',
      'de': 'heim',
      'el': 'σπίτι',
      'en': 'home',
      'es': 'hogar',
      'et': 'kodu',
      'eu': 'etxea',
      'fa': 'خانه',
      'fi': 'kotiin',
      'fr': 'maison',
      'gl': 'fogar',
      'gu': 'ઘર',
      'he': 'בַּיִת',
      'hi': 'घर',
      'hr': 'dom',
      'hu': 'otthon',
      'hy': 'տուն',
      'id': 'rumah',
      'is': 'heim',
      'it': 'casa',
      'ja': 'ホーム',
      'ka': 'სახლი',
      'kk': 'үй',
      'km': 'ផ្ទះ',
      'kn': 'ಮನೆ',
      'ky': 'үй',
      'lo': 'ບ້ານ',
      'lt': 'namai',
      'lv': 'mājas',
      'mk': 'дом',
      'ml': 'വീട്',
      'mn': 'гэр',
      'mr': 'घर',
      'ms': 'rumah',
      'my': 'အိမ်',
      'ne': 'घर',
      'nl': 'thuis',
      'no': 'hjem',
      'or': 'ଘର',
      'pa': 'ਘਰ',
      'pl': 'dom',
      'ps': 'کور',
      'pt': 'lar',
      'ro': 'acasă',
      'ru': 'дом',
      'sd': 'گھر',
      'si': 'නිවස',
      'sk': 'domov',
      'sl': 'dom',
      'sm': 'aiga',
      'sq': 'shtëpi',
      'sr': 'дом',
      'sv': 'hem',
      'sw': 'nyumbani',
      'ta': 'வீடு',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tl': 'bahay',
      'tr': 'Ev',
      'uk': 'дім',
      'ur': 'گھر',
      'uz': 'uy',
      'vi': 'trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
      'zu': 'ekhaya',
    },
  },
  // Miscellaneous
  {
    'kn3ew2kr': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    't3gwbg8p': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '32zk3bsy': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'fxpycar9': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'zoczg7f5': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '4veq8lhu': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '24jkc6kz': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'ql3mktqp': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'uuuyi67d': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '2j0itvs6': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'm3ckegay': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '03lowxor': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'm6lxdeji': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'bby3aosb': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'sga2c9gb': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'rgxcnjeh': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'ockfij0i': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '82b48a55': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'vydqirqk': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '0e1f0ugr': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'mzhnni6u': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'nkw2ujs4': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'dr2uyv6g': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '9f6lkupu': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'an54bfaa': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
  },
].reduce((a, b) => a..addAll(b));
