import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'ko',
        'en',
        'ja',
        'zh_Hans',
        'zh_Hant',
        'it',
        'fr',
        'de',
        'nl',
        'es',
        'ar',
        'vi',
        'ta',
        'th',
        'tr',
        'uk',
        'id',
        'ms',
        'pl',
        'pt',
        'sv',
        'da',
        'hu',
        'el',
        'he',
        'hi',
        'lv',
        'ne',
        'mn',
        'uz',
        'sl',
        'ro',
        'ml',
        'no',
        'ru',
        'sk',
        'fa',
        'af',
        'az',
        'am',
        'eu',
        'be',
        'bn',
        'my',
        'bs',
        'bg',
        'km',
        'sq',
        'cs',
        'hr',
        'et',
        'hy',
        'fi',
        'ka',
        'gu',
        'is',
        'gl',
        'kn',
        'kk',
        'lo',
        'mk',
        'mr',
        'lt',
        'ca',
        'or',
        'pa',
        'ps',
        'sr',
        'sm',
        'si',
        'sw',
        'te',
        'sd',
        'tl',
        'ur',
        'ky',
        'zu'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? koText = '',
    String? enText = '',
    String? jaText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? itText = '',
    String? frText = '',
    String? deText = '',
    String? nlText = '',
    String? esText = '',
    String? arText = '',
    String? viText = '',
    String? taText = '',
    String? thText = '',
    String? trText = '',
    String? ukText = '',
    String? idText = '',
    String? msText = '',
    String? plText = '',
    String? ptText = '',
    String? svText = '',
    String? daText = '',
    String? huText = '',
    String? elText = '',
    String? heText = '',
    String? hiText = '',
    String? lvText = '',
    String? neText = '',
    String? mnText = '',
    String? uzText = '',
    String? slText = '',
    String? roText = '',
    String? mlText = '',
    String? noText = '',
    String? ruText = '',
    String? skText = '',
    String? faText = '',
    String? afText = '',
    String? azText = '',
    String? amText = '',
    String? euText = '',
    String? beText = '',
    String? bnText = '',
    String? myText = '',
    String? bsText = '',
    String? bgText = '',
    String? kmText = '',
    String? sqText = '',
    String? csText = '',
    String? hrText = '',
    String? etText = '',
    String? hyText = '',
    String? fiText = '',
    String? kaText = '',
    String? guText = '',
    String? isText = '',
    String? glText = '',
    String? knText = '',
    String? kkText = '',
    String? loText = '',
    String? mkText = '',
    String? mrText = '',
    String? ltText = '',
    String? caText = '',
    String? orText = '',
    String? paText = '',
    String? psText = '',
    String? srText = '',
    String? smText = '',
    String? siText = '',
    String? swText = '',
    String? teText = '',
    String? sdText = '',
    String? tlText = '',
    String? urText = '',
    String? kyText = '',
    String? zuText = '',
  }) =>
      [
        koText,
        enText,
        jaText,
        zh_HansText,
        zh_HantText,
        itText,
        frText,
        deText,
        nlText,
        esText,
        arText,
        viText,
        taText,
        thText,
        trText,
        ukText,
        idText,
        msText,
        plText,
        ptText,
        svText,
        daText,
        huText,
        elText,
        heText,
        hiText,
        lvText,
        neText,
        mnText,
        uzText,
        slText,
        roText,
        mlText,
        noText,
        ruText,
        skText,
        faText,
        afText,
        azText,
        amText,
        euText,
        beText,
        bnText,
        myText,
        bsText,
        bgText,
        kmText,
        sqText,
        csText,
        hrText,
        etText,
        hyText,
        fiText,
        kaText,
        guText,
        isText,
        glText,
        knText,
        kkText,
        loText,
        mkText,
        mrText,
        ltText,
        caText,
        orText,
        paText,
        psText,
        srText,
        smText,
        siText,
        swText,
        teText,
        sdText,
        tlText,
        urText,
        kyText,
        zuText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'c0ob4q61': {
      'ko': '꺼짐',
      'af': 'Af',
      'am': 'ጠፍቷል',
      'ar': 'عن',
      'az': 'Söndür',
      'be': 'Выключана',
      'bg': 'Изключено',
      'bn': 'বন্ধ',
      'bs': 'Isključeno',
      'ca': 'Desactivat',
      'cs': 'Vypnuto',
      'da': 'Slukket',
      'de': 'Aus',
      'el': 'Μακριά από',
      'en': 'Off',
      'es': 'Apagado',
      'et': 'Väljas',
      'eu': 'Itzalita',
      'fa': 'خاموش',
      'fi': 'Pois',
      'fr': 'Désactivé',
      'gl': 'Desactivado',
      'gu': 'બંધ',
      'he': 'כבוי',
      'hi': 'बंद',
      'hr': 'Isključeno',
      'hu': 'Le',
      'hy': 'Անջատված',
      'id': 'Mati',
      'is': 'Slökkt',
      'it': 'Spento',
      'ja': 'オフ',
      'ka': 'გამორთულია',
      'kk': 'Өшірулі',
      'km': 'បិទ',
      'kn': 'ಆಫ್',
      'ky': 'Өчүк',
      'lo': 'ປິດ',
      'lt': 'Išjungta',
      'lv': 'Izslēgts',
      'mk': 'Исклучено',
      'ml': 'ഓഫ്',
      'mn': 'Унтраах',
      'mr': 'बंद',
      'ms': 'Mati',
      'my': 'ပိတ်သည်။',
      'ne': 'बन्द',
      'nl': 'Uit',
      'no': 'Av',
      'or': 'ବନ୍ଦ ଅଛି',
      'pa': 'ਬੰਦ',
      'pl': 'Wyłączony',
      'ps': 'بند',
      'pt': 'Desligado',
      'ro': 'Dezactivat',
      'ru': 'Выключенный',
      'sd': 'بند',
      'si': 'අක්‍රියයි',
      'sk': 'Vypnuté',
      'sl': 'Izklopljeno',
      'sm': 'Tape',
      'sq': 'Joaktiv',
      'sr': 'Искључено',
      'sv': 'Av',
      'sw': 'Imezimwa',
      'ta': 'ஆஃப்',
      'te': 'ఆఫ్',
      'th': 'ปิด',
      'tl': 'Naka-off',
      'tr': 'Kapalı',
      'uk': 'Вимкнено',
      'ur': 'آف',
      'uz': 'Oʻchirilgan',
      'vi': 'Tắt',
      'zh_Hans': '离开',
      'zh_Hant': '離開',
      'zu': 'Valiwe',
    },
    '24qab3qx': {
      'ko': '켜짐',
      'af': 'Aan',
      'am': 'በርቷል',
      'ar': 'على',
      'az': 'Aktiv',
      'be': 'Уключана',
      'bg': 'Включено',
      'bn': 'চালু',
      'bs': 'Uključeno',
      'ca': 'Activat',
      'cs': 'Na',
      'da': 'På',
      'de': 'An',
      'el': 'Επί',
      'en': 'On',
      'es': 'En',
      'et': 'Sees',
      'eu': 'Piztuta',
      'fa': 'روشن',
      'fi': 'Päällä',
      'fr': 'Sur',
      'gl': 'Activado',
      'gu': 'ચાલુ',
      'he': 'עַל',
      'hi': 'पर',
      'hr': 'Na',
      'hu': 'On',
      'hy': 'Միացված է',
      'id': 'Pada',
      'is': 'Kveikt',
      'it': 'SU',
      'ja': '点灯',
      'ka': 'ჩართულია',
      'kk': 'Қосулы',
      'km': 'បើក',
      'kn': 'ಆನ್',
      'ky': 'Күйүк',
      'lo': 'ສຸດ',
      'lt': 'Įjungta',
      'lv': 'Ieslēgts',
      'mk': 'Вклучено',
      'ml': 'ഓൺ',
      'mn': 'Асаалттай',
      'mr': 'चालू',
      'ms': 'hidup',
      'my': 'ဂရန်',
      'ne': 'खुल्ला',
      'nl': 'Op',
      'no': 'På',
      'or': 'ଅନ୍',
      'pa': 'ਚਾਲੂ',
      'pl': 'NA',
      'ps': 'په',
      'pt': 'Sobre',
      'ro': 'Pe',
      'ru': 'На',
      'sd': 'تي',
      'si': 'ක්‍රියාත්මකයි',
      'sk': 'Zapnuté',
      'sl': 'Vklopljeno',
      'sm': 'luga',
      'sq': 'Aktiv',
      'sr': 'Укључено',
      'sv': 'På',
      'sw': 'Washa',
      'ta': 'அன்று',
      'te': 'ఆన్',
      'th': 'บน',
      'tl': 'Naka-on',
      'tr': 'Açık',
      'uk': 'Увімкнено',
      'ur': 'پر',
      'uz': 'Yoniq',
      'vi': 'TRÊN',
      'zh_Hans': '在',
      'zh_Hant': '在',
      'zu': 'Vuliwe',
    },
    'iq5z1i00': {
      'ko': '손전등',
      'af': 'Flitslig',
      'am': 'የእጅ ባትሪ',
      'ar': 'مصباح يدوي',
      'az': 'Fənər',
      'be': 'Ліхтарык',
      'bg': 'Фенерче',
      'bn': 'টর্চলাইট',
      'bs': 'Svjetiljka',
      'ca': 'Llanterna',
      'cs': 'Svítilna',
      'da': 'Lommelygte',
      'de': 'Taschenlampe',
      'el': 'Φακός',
      'en': 'Flashlight',
      'es': 'Flash',
      'et': 'Taskulamp',
      'eu': 'Linterna',
      'fa': 'چراغ قوه',
      'fi': 'Taskulamppu',
      'fr': 'Lampe de poche',
      'gl': 'Lanterna',
      'gu': 'ફ્લેશલાઇટ',
      'he': 'פָּנַס כִּיס',
      'hi': 'टॉर्च',
      'hr': 'Svjetiljka',
      'hu': 'Zseblámpa',
      'hy': 'Լապտեր',
      'id': 'Senter',
      'is': 'Vasaljós',
      'it': 'Torcia elettrica',
      'ja': '懐中電灯',
      'ka': 'ფანარი',
      'kk': 'Фонар',
      'km': 'ពិល',
      'kn': 'ಫ್ಲ್ಯಾಶ್‌ಲೈಟ್',
      'ky': 'Кол чырак',
      'lo': 'ໄຟສາຍ',
      'lt': 'Žibintuvėlis',
      'lv': 'Lukturītis',
      'mk': 'Фенерче',
      'ml': 'ഫ്ലാഷ്‌ലൈറ്റ്',
      'mn': 'Гар чийдэн',
      'mr': 'टॉर्च',
      'ms': 'Lampu suluh',
      'my': 'ဓာတ်မီး',
      'ne': 'टर्चलाइट',
      'nl': 'Zaklamp',
      'no': 'Lommelykt',
      'or': 'ଫ୍ଲାସଲାଇଟ୍',
      'pa': 'ਫਲੈਸ਼ਲਾਈਟ',
      'pl': 'Flesz',
      'ps': 'لاسي څراغ',
      'pt': 'Lanterna',
      'ro': 'Lanternă',
      'ru': 'Фонарик',
      'sd': 'ٽارچ',
      'si': 'ෆ්ලෑෂ් ලයිට්',
      'sk': 'Baterka',
      'sl': 'Svetilka',
      'sm': 'moliuila',
      'sq': 'Fener',
      'sr': 'Батеријска лампа',
      'sv': 'Ficklampa',
      'sw': 'Tochi',
      'ta': 'பிரகாச ஒளி',
      'te': 'ఫ్లాష్‌లైట్',
      'th': 'ไฟฉาย',
      'tl': 'Flashlight',
      'tr': 'El feneri',
      'uk': 'Ліхтарик',
      'ur': 'ٹارچ',
      'uz': 'Chiroq',
      'vi': 'Đèn pin',
      'zh_Hans': '手电筒',
      'zh_Hant': '手電筒',
      'zu': 'Ithoshi',
    },
    'pumtmx3a': {
      'ko': '홈',
      'af': 'huis',
      'am': 'ቤት',
      'ar': 'بيت',
      'az': 'ev',
      'be': 'дом',
      'bg': 'дом',
      'bn': 'বাড়ি',
      'bs': 'dom',
      'ca': 'casa',
      'cs': 'domov',
      'da': 'hjem',
      'de': 'heim',
      'el': 'σπίτι',
      'en': 'home',
      'es': 'hogar',
      'et': 'kodu',
      'eu': 'etxea',
      'fa': 'خانه',
      'fi': 'kotiin',
      'fr': 'maison',
      'gl': 'fogar',
      'gu': 'ઘર',
      'he': 'בַּיִת',
      'hi': 'घर',
      'hr': 'dom',
      'hu': 'otthon',
      'hy': 'տուն',
      'id': 'rumah',
      'is': 'heim',
      'it': 'casa',
      'ja': 'ホーム',
      'ka': 'სახლი',
      'kk': 'үй',
      'km': 'ផ្ទះ',
      'kn': 'ಮನೆ',
      'ky': 'үй',
      'lo': 'ບ້ານ',
      'lt': 'namai',
      'lv': 'mājas',
      'mk': 'дом',
      'ml': 'വീട്',
      'mn': 'гэр',
      'mr': 'घर',
      'ms': 'rumah',
      'my': 'အိမ်',
      'ne': 'घर',
      'nl': 'thuis',
      'no': 'hjem',
      'or': 'ଘର',
      'pa': 'ਘਰ',
      'pl': 'dom',
      'ps': 'کور',
      'pt': 'lar',
      'ro': 'acasă',
      'ru': 'дом',
      'sd': 'گھر',
      'si': 'නිවස',
      'sk': 'domov',
      'sl': 'dom',
      'sm': 'aiga',
      'sq': 'shtëpi',
      'sr': 'дом',
      'sv': 'hem',
      'sw': 'nyumbani',
      'ta': 'வீடு',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tl': 'bahay',
      'tr': 'Ev',
      'uk': 'дім',
      'ur': 'گھر',
      'uz': 'uy',
      'vi': 'trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
      'zu': 'ekhaya',
    },
    'n4v8t2q6': {
      'ko': '이 기기는 플래시가 없어 화면을 밝힙니다',
      'af': 'Hierdie toestel het geen flits nie, daarom word die skerm verhelder',
      'am': 'ይህ መሣሪያ ብልጭታ የለውም፤ ስለዚህ ማያ ገጹ ይበራል',
      'ar': 'لا يحتوي هذا الجهاز على فلاش، لذا تتم إضاءة الشاشة',
      'az': 'Bu cihazda flaş yoxdur, ona görə ekran işıqlandırılır',
      'be': 'На гэтай прыладзе няма ўспышкі, таму падсвятляецца экран',
      'bg': 'Това устройство няма светкавица, затова екранът се осветява',
      'bn': 'এই ডিভাইসে ফ্ল্যাশ নেই, তাই স্ক্রিন উজ্জ্বল করা হচ্ছে',
      'bs': 'Ovaj uređaj nema bljeskalicu, pa se osvjetljava ekran',
      'ca': 'Aquest dispositiu no té flaix, així que s’il·lumina la pantalla',
      'cs': 'Toto zařízení nemá blesk, proto se rozsvítí obrazovka',
      'da': 'Denne enhed har ingen blitz, så skærmen lyser op',
      'de': 'Dieses Gerät hat kein Blitzlicht, daher wird der Bildschirm aufgehellt',
      'el': 'Αυτή η συσκευή δεν έχει φλας, γι’ αυτό φωτίζεται η οθόνη',
      'en': 'This device has no flash, so the screen is used as the light',
      'es': 'Este dispositivo no tiene flash, por lo que se ilumina la pantalla',
      'et': 'Sellel seadmel pole välku, seetõttu valgustatakse ekraani',
      'eu': 'Gailu honek ez du flashik, beraz pantaila argitzen da',
      'fa': 'این دستگاه فلش ندارد، بنابراین صفحه روشن می‌شود',
      'fi': 'Tässä laitteessa ei ole salamaa, joten näyttö kirkastetaan',
      'fr': 'Cet appareil n’a pas de flash, l’écran sert donc de lampe',
      'gl': 'Este dispositivo non ten flash, así que se ilumina a pantalla',
      'gu': 'આ ઉપકરણમાં ફ્લેશ નથી, તેથી સ્ક્રીન પ્રકાશિત કરવામાં આવે છે',
      'he': 'במכשיר זה אין פלאש, ולכן המסך מואר',
      'hi': 'इस डिवाइस में फ़्लैश नहीं है, इसलिए स्क्रीन को रोशन किया जाता है',
      'hr': 'Ovaj uređaj nema bljeskalicu pa se osvjetljava zaslon',
      'hu': 'Ezen az eszközön nincs vaku, ezért a képernyő világít',
      'hy': 'Այս սարքը լապտեր չունի, ուստի լուսավորվում է էկրանը',
      'id': 'Perangkat ini tidak memiliki lampu kilat, jadi layar yang dinyalakan',
      'is': 'Þetta tæki er ekki með flass, því lýsist skjárinn upp',
      'it': 'Questo dispositivo non ha il flash, quindi viene illuminato lo schermo',
      'ja': 'この端末にはフラッシュがないため、画面を明るくします',
      'ka': 'ამ მოწყობილობას ფლეში არ აქვს, ამიტომ ნათდება ეკრანი',
      'kk': 'Бұл құрылғыда жарқылдақ жоқ, сондықтан экран жарықтандырылады',
      'km': 'ឧបករណ៍នេះមិនមានពន្លឺហ្វ្លាស់ទេ ដូច្នេះអេក្រង់ត្រូវបានបំភ្លឺ',
      'kn': 'ಈ ಸಾಧನದಲ್ಲಿ ಫ್ಲ್ಯಾಶ್ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಪರದೆಯನ್ನು ಬೆಳಗಿಸಲಾಗುತ್ತದೆ',
      'ky': 'Бул түзмөктө жарык жок, ошондуктан экран жарыктандырылат',
      'lo': 'ອຸປະກອນນີ້ບໍ່ມີແຟລດ ດັ່ງນັ້ນຈຶ່ງເປີດແສງໜ້າຈໍແທນ',
      'lt': 'Šiame įrenginyje nėra blykstės, todėl apšviečiamas ekranas',
      'lv': 'Šai ierīcei nav zibspuldzes, tāpēc tiek izgaismots ekrāns',
      'mk': 'Овој уред нема блиц, затоа се осветлува екранот',
      'ml': 'ഈ ഉപകരണത്തിൽ ഫ്ലാഷ് ഇല്ല, അതിനാൽ സ്ക്രീൻ പ്രകാശിപ്പിക്കുന്നു',
      'mn': 'Энэ төхөөрөмжид гэрэлтүүлэг байхгүй тул дэлгэцийг гэрэлтүүлнэ',
      'mr': 'या डिव्हाइसमध्ये फ्लॅश नाही, म्हणून स्क्रीन उजळवली जाते',
      'ms': 'Peranti ini tiada lampu denyar, jadi skrin dicerahkan',
      'my': 'ဤစက်တွင် ဖလက်ရှ်မရှိသဖြင့် ဖန်သားပြင်ကို လင်းစေပါသည်',
      'ne': 'यो यन्त्रमा फ्ल्यास छैन, त्यसैले स्क्रिन उज्यालो पारिन्छ',
      'nl': 'Dit apparaat heeft geen flitser, daarom wordt het scherm verlicht',
      'no': 'Denne enheten har ingen blits, så skjermen lyser opp',
      'or': 'ଏହି ଡିଭାଇସରେ ଫ୍ଲାସ୍ ନାହିଁ, ତେଣୁ ସ୍କ୍ରିନ୍ ଆଲୋକିତ ହୁଏ',
      'pa': 'ਇਸ ਡੀਵਾਈਸ ਵਿੱਚ ਫਲੈਸ਼ ਨਹੀਂ ਹੈ, ਇਸ ਲਈ ਸਕ੍ਰੀਨ ਨੂੰ ਰੌਸ਼ਨ ਕੀਤਾ ਜਾਂਦਾ ਹੈ',
      'pl': 'To urządzenie nie ma lampy błyskowej, dlatego rozjaśniany jest ekran',
      'ps': 'دا وسیله فلش نه لري، نو سکرین روښانه کیږي',
      'pt': 'Este dispositivo não tem flash, então a tela é iluminada',
      'ro': 'Acest dispozitiv nu are bliț, așa că este luminat ecranul',
      'ru': 'На этом устройстве нет вспышки, поэтому подсвечивается экран',
      'sd': 'هن ڊوائيس ۾ فليش ناهي، تنهنڪري اسڪرين روشن ڪئي وڃي ٿي',
      'si': 'මෙම උපාංගයේ ෆ්ලෑෂ් නොමැති නිසා තිරය දීප්තිමත් කෙරේ',
      'sk': 'Toto zariadenie nemá blesk, preto sa rozsvieti obrazovka',
      'sl': 'Ta naprava nima bliskavice, zato se osvetli zaslon',
      'sm': 'E leai se moli o lenei masini, o lea e faamalamalamaina ai le lau',
      'sq': 'Kjo pajisje nuk ka blic, prandaj ndriçohet ekrani',
      'sr': 'Овај уређај нема блиц, па се осветљава екран',
      'sv': 'Den här enheten har ingen blixt, så skärmen lyses upp',
      'sw': 'Kifaa hiki hakina mweko, kwa hivyo skrini huwashwa',
      'ta': 'இந்தச் சாதனத்தில் ஃபிளாஷ் இல்லை, எனவே திரை ஒளிரச் செய்யப்படுகிறது',
      'te': 'ఈ పరికరంలో ఫ్లాష్ లేదు, కాబట్టి స్క్రీన్ ప్రకాశవంతం చేయబడుతుంది',
      'th': 'อุปกรณ์นี้ไม่มีแฟลช จึงใช้หน้าจอส่องสว่างแทน',
      'tl': 'Walang flash ang device na ito, kaya ang screen ang pinapaliwanag',
      'tr': 'Bu cihazda flaş yok, bu yüzden ekran aydınlatılıyor',
      'uk': 'На цьому пристрої немає спалаху, тому підсвічується екран',
      'ur': 'اس ڈیوائس میں فلیش نہیں ہے، اس لیے اسکرین کو روشن کیا جاتا ہے',
      'uz': 'Bu qurilmada chaqnoq yo‘q, shuning uchun ekran yoritiladi',
      'vi': 'Thiết bị này không có đèn flash nên màn hình được làm sáng',
      'zh_Hans': '此设备没有闪光灯，因此点亮屏幕',
      'zh_Hant': '此裝置沒有閃光燈，因此點亮螢幕',
      'zu': 'Le divayisi ayinalo ilambu, ngakho isikrini siyakhanyiswa',
    },
    'q7w3e5r1': {
      'ko': '확인',
      'af': 'Reg so',
      'am': 'እሺ',
      'ar': 'حسنًا',
      'az': 'Tamam',
      'be': 'Добра',
      'bg': 'Добре',
      'bn': 'ঠিক আছে',
      'bs': 'U redu',
      'ca': 'D\'acord',
      'cs': 'OK',
      'da': 'OK',
      'de': 'OK',
      'el': 'Εντάξει',
      'en': 'OK',
      'es': 'Aceptar',
      'et': 'Selge',
      'eu': 'Ados',
      'fa': 'باشه',
      'fi': 'OK',
      'fr': 'D\'accord',
      'gl': 'Aceptar',
      'gu': 'ઠીક છે',
      'he': 'אישור',
      'hi': 'ठीक है',
      'hr': 'U redu',
      'hu': 'Rendben',
      'hy': 'Լավ',
      'id': 'Oke',
      'is': 'Í lagi',
      'it': 'OK',
      'ja': 'OK',
      'ka': 'კარგი',
      'kk': 'Жарайды',
      'km': 'យល់ព្រម',
      'kn': 'ಸರಿ',
      'ky': 'Жарайт',
      'lo': 'ຕົກລົງ',
      'lt': 'Gerai',
      'lv': 'Labi',
      'mk': 'Во ред',
      'ml': 'ശരി',
      'mn': 'Ойлголоо',
      'mr': 'ठीक आहे',
      'ms': 'OK',
      'my': 'ကောင်းပြီ',
      'ne': 'ठीक छ',
      'nl': 'Oké',
      'no': 'OK',
      'or': 'ଠିକ୍ ଅଛି',
      'pa': 'ਠੀਕ ਹੈ',
      'pl': 'OK',
      'ps': 'سمه ده',
      'pt': 'OK',
      'ro': 'OK',
      'ru': 'Понятно',
      'sd': 'ٺيڪ آهي',
      'si': 'හරි',
      'sk': 'OK',
      'sl': 'V redu',
      'sm': 'Ua lelei',
      'sq': 'Në rregull',
      'sr': 'У реду',
      'sv': 'OK',
      'sw': 'Sawa',
      'ta': 'சரி',
      'te': 'సరే',
      'th': 'ตกลง',
      'tl': 'OK',
      'tr': 'Tamam',
      'uk': 'Зрозуміло',
      'ur': 'ٹھیک ہے',
      'uz': 'Tushunarli',
      'vi': 'Đã hiểu',
      'zh_Hans': '知道了',
      'zh_Hant': '知道了',
      'zu': 'Kulungile',
    },
  },
  // Miscellaneous
  {
    'kn3ew2kr': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    't3gwbg8p': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '32zk3bsy': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'fxpycar9': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'zoczg7f5': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '4veq8lhu': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '24jkc6kz': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'ql3mktqp': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'uuuyi67d': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '2j0itvs6': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'm3ckegay': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '03lowxor': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'm6lxdeji': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'bby3aosb': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'sga2c9gb': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'rgxcnjeh': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'ockfij0i': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '82b48a55': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'vydqirqk': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '0e1f0ugr': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'mzhnni6u': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'nkw2ujs4': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'dr2uyv6g': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '9f6lkupu': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'an54bfaa': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
  },
].reduce((a, b) => a..addAll(b));
