import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'ko',
        'en',
        'ja',
        'zh_Hans',
        'zh_Hant',
        'it',
        'fr',
        'de',
        'nl',
        'es',
        'ar',
        'vi',
        'ta',
        'th',
        'tr',
        'uk',
        'id',
        'ms',
        'pl',
        'pt',
        'sv',
        'da',
        'hu',
        'el',
        'he',
        'hi',
        'lv',
        'ne',
        'mn',
        'uz',
        'sl',
        'ro',
        'ml',
        'no',
        'ru',
        'sk',
        'fa',
        'af',
        'az',
        'am',
        'eu',
        'be',
        'bn',
        'my',
        'bs',
        'bg',
        'km',
        'sq',
        'cs',
        'hr',
        'et',
        'hy',
        'fi',
        'ka',
        'gu',
        'is',
        'gl',
        'kn',
        'kk',
        'lo',
        'mk',
        'mr',
        'lt',
        'ca',
        'or',
        'pa',
        'ps',
        'sr',
        'sm',
        'si',
        'sw',
        'te',
        'sd',
        'tl',
        'ur',
        'ky',
        'zu'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  /// [getText] 와 같지만, 이 로케일에 번역이 없으면 en 을, 그것도 없으면 ko 를
  /// 돌려준다.
  ///
  /// [getText] 는 없는 로케일에 빈 문자열을 준다. 이 앱은 77개 언어를
  /// 선언하므로 새 문구에서 한 언어라도 빠지면 그 언어에서는 글자가 통째로
  /// 사라진다. 기존 호출부의 동작을 바꾸지 않으려고 [getText] 는 그대로 두고
  /// 이걸 따로 뒀다.
  String getTextOr(String key) {
    final translations = kTranslationsMap[key] ?? const <String, String>{};
    for (final candidate in <String>[locale.toString(), 'en', 'ko']) {
      final value = translations[candidate];
      if (value != null && value.isNotEmpty) {
        return value;
      }
    }
    return '';
  }

  String getVariableText({
    String? koText = '',
    String? enText = '',
    String? jaText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? itText = '',
    String? frText = '',
    String? deText = '',
    String? nlText = '',
    String? esText = '',
    String? arText = '',
    String? viText = '',
    String? taText = '',
    String? thText = '',
    String? trText = '',
    String? ukText = '',
    String? idText = '',
    String? msText = '',
    String? plText = '',
    String? ptText = '',
    String? svText = '',
    String? daText = '',
    String? huText = '',
    String? elText = '',
    String? heText = '',
    String? hiText = '',
    String? lvText = '',
    String? neText = '',
    String? mnText = '',
    String? uzText = '',
    String? slText = '',
    String? roText = '',
    String? mlText = '',
    String? noText = '',
    String? ruText = '',
    String? skText = '',
    String? faText = '',
    String? afText = '',
    String? azText = '',
    String? amText = '',
    String? euText = '',
    String? beText = '',
    String? bnText = '',
    String? myText = '',
    String? bsText = '',
    String? bgText = '',
    String? kmText = '',
    String? sqText = '',
    String? csText = '',
    String? hrText = '',
    String? etText = '',
    String? hyText = '',
    String? fiText = '',
    String? kaText = '',
    String? guText = '',
    String? isText = '',
    String? glText = '',
    String? knText = '',
    String? kkText = '',
    String? loText = '',
    String? mkText = '',
    String? mrText = '',
    String? ltText = '',
    String? caText = '',
    String? orText = '',
    String? paText = '',
    String? psText = '',
    String? srText = '',
    String? smText = '',
    String? siText = '',
    String? swText = '',
    String? teText = '',
    String? sdText = '',
    String? tlText = '',
    String? urText = '',
    String? kyText = '',
    String? zuText = '',
  }) =>
      [
        koText,
        enText,
        jaText,
        zh_HansText,
        zh_HantText,
        itText,
        frText,
        deText,
        nlText,
        esText,
        arText,
        viText,
        taText,
        thText,
        trText,
        ukText,
        idText,
        msText,
        plText,
        ptText,
        svText,
        daText,
        huText,
        elText,
        heText,
        hiText,
        lvText,
        neText,
        mnText,
        uzText,
        slText,
        roText,
        mlText,
        noText,
        ruText,
        skText,
        faText,
        afText,
        azText,
        amText,
        euText,
        beText,
        bnText,
        myText,
        bsText,
        bgText,
        kmText,
        sqText,
        csText,
        hrText,
        etText,
        hyText,
        fiText,
        kaText,
        guText,
        isText,
        glText,
        knText,
        kkText,
        loText,
        mkText,
        mrText,
        ltText,
        caText,
        orText,
        paText,
        psText,
        srText,
        smText,
        siText,
        swText,
        teText,
        sdText,
        tlText,
        urText,
        kyText,
        zuText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    // 광고 제거 인앱 결제 (lib/flutter_flow/remove_ads_promo.dart).
    // 값을 읽을 때는 getText 가 아니라 getTextOr 를 쓴다.
    'rmad0001': {
      'ko': '광고 없이 사용하기',
      'af': 'Gebruik sonder advertensies',
      'am': 'ያለ ማስታወቂያ ይጠቀሙ',
      'ar': 'استخدم بدون إعلانات',
      'az': 'Reklamsız istifadə edin',
      'be': 'Карыстацца без рэкламы',
      'bg': 'Използвайте без реклами',
      'bn': 'বিজ্ঞাপন ছাড়া ব্যবহার করুন',
      'bs': 'Koristite bez reklama',
      'ca': 'Utilitza\'l sense anuncis',
      'cs': 'Používat bez reklam',
      'da': 'Brug uden annoncer',
      'de': 'Ohne Werbung nutzen',
      'el': 'Χρήση χωρίς διαφημίσεις',
      'en': 'Use without ads',
      'es': 'Usar sin anuncios',
      'et': 'Kasuta ilma reklaamideta',
      'eu': 'Erabili iragarkirik gabe',
      'fa': 'استفاده بدون تبلیغات',
      'fi': 'Käytä ilman mainoksia',
      'fr': 'Utiliser sans publicité',
      'gl': 'Usar sen anuncios',
      'gu': 'જાહેરાત વિના વાપરો',
      'he': 'שימוש ללא פרסומות',
      'hi': 'बिना विज्ञापन के उपयोग करें',
      'hr': 'Koristi bez oglasa',
      'hu': 'Használat hirdetések nélkül',
      'hy': 'Օգտագործել առանց գովազդի',
      'id': 'Gunakan tanpa iklan',
      'is': 'Nota án auglýsinga',
      'it': 'Usa senza pubblicità',
      'ja': '広告なしで使う',
      'ka': 'გამოიყენეთ რეკლამის გარეშე',
      'kk': 'Жарнамасыз пайдалану',
      'km': 'ប្រើដោយគ្មានការផ្សាយពាណិជ្ជកម្ម',
      'kn': 'ಜಾಹೀರಾತು ಇಲ್ಲದೆ ಬಳಸಿ',
      'ky': 'Жарнамасыз колдонуу',
      'lo': 'ໃຊ້ໂດຍບໍ່ມີໂຄສະນາ',
      'lt': 'Naudoti be skelbimų',
      'lv': 'Lietot bez reklāmām',
      'mk': 'Користете без реклами',
      'ml': 'പരസ്യങ്ങളില്ലാതെ ഉപയോഗിക്കുക',
      'mn': 'Сурталчилгаагүй ашиглах',
      'mr': 'जाहिरातींशिवाय वापरा',
      'ms': 'Guna tanpa iklan',
      'my': 'ကြော်ငြာမပါဘဲ သုံးပါ',
      'ne': 'विज्ञापनविना प्रयोग गर्नुहोस्',
      'nl': 'Gebruiken zonder advertenties',
      'no': 'Bruk uten annonser',
      'or': 'ବିଜ୍ଞାପନ ବିନା ବ୍ୟବହାର କରନ୍ତୁ',
      'pa': 'ਇਸ਼ਤਿਹਾਰਾਂ ਤੋਂ ਬਿਨਾਂ ਵਰਤੋ',
      'pl': 'Korzystaj bez reklam',
      'ps': 'پرته له اعلانونو یې وکاروئ',
      'pt': 'Usar sem anúncios',
      'ro': 'Folosește fără reclame',
      'ru': 'Пользоваться без рекламы',
      'sd': 'اشتهارن کان سواءِ استعمال ڪريو',
      'si': 'දැන්වීම් නොමැතිව භාවිත කරන්න',
      'sk': 'Používať bez reklám',
      'sl': 'Uporabljaj brez oglasov',
      'sm': 'Fa’aaogā e aunoa ma faasalalauga',
      'sq': 'Përdore pa reklama',
      'sr': 'Користи без огласа',
      'sv': 'Använd utan annonser',
      'sw': 'Tumia bila matangazo',
      'ta': 'விளம்பரம் இல்லாமல் பயன்படுத்து',
      'te': 'ప్రకటనలు లేకుండా ఉపయోగించండి',
      'th': 'ใช้งานโดยไม่มีโฆษณา',
      'tl': 'Gamitin nang walang ad',
      'tr': 'Reklamsız kullan',
      'uk': 'Користуватися без реклами',
      'ur': 'اشتہارات کے بغیر استعمال کریں',
      'uz': 'Reklamasiz foydalanish',
      'vi': 'Dùng không quảng cáo',
      'zh_Hans': '无广告使用',
      'zh_Hant': '無廣告使用',
      'zu': 'Sebenzisa ngaphandle kwezikhangiso',
    },
    'rmad0002': {
      'ko': '구매',
      'af': 'Koop',
      'am': 'ግዛ',
      'ar': 'شراء',
      'az': 'Al',
      'be': 'Купіць',
      'bg': 'Купи',
      'bn': 'কিনুন',
      'bs': 'Kupi',
      'ca': 'Compra',
      'cs': 'Koupit',
      'da': 'Køb',
      'de': 'Kaufen',
      'el': 'Αγορά',
      'en': 'Buy',
      'es': 'Comprar',
      'et': 'Osta',
      'eu': 'Erosi',
      'fa': 'خرید',
      'fi': 'Osta',
      'fr': 'Acheter',
      'gl': 'Comprar',
      'gu': 'ખરીદો',
      'he': 'קנה',
      'hi': 'खरीदें',
      'hr': 'Kupi',
      'hu': 'Megvásárlás',
      'hy': 'Գնել',
      'id': 'Beli',
      'is': 'Kaupa',
      'it': 'Acquista',
      'ja': '購入',
      'ka': 'ყიდვა',
      'kk': 'Сатып алу',
      'km': 'ទិញ',
      'kn': 'ಖರೀದಿಸಿ',
      'ky': 'Сатып алуу',
      'lo': 'ຊື້',
      'lt': 'Pirkti',
      'lv': 'Pirkt',
      'mk': 'Купи',
      'ml': 'വാങ്ങുക',
      'mn': 'Худалдаж авах',
      'mr': 'खरेदी करा',
      'ms': 'Beli',
      'my': 'ဝယ်ယူရန်',
      'ne': 'किन्नुहोस्',
      'nl': 'Kopen',
      'no': 'Kjøp',
      'or': 'କିଣନ୍ତୁ',
      'pa': 'ਖਰੀਦੋ',
      'pl': 'Kup',
      'ps': 'واخلئ',
      'pt': 'Comprar',
      'ro': 'Cumpără',
      'ru': 'Купить',
      'sd': 'خريدو',
      'si': 'මිලදී ගන්න',
      'sk': 'Kúpiť',
      'sl': 'Kupi',
      'sm': 'Fa’atau',
      'sq': 'Blej',
      'sr': 'Купи',
      'sv': 'Köp',
      'sw': 'Nunua',
      'ta': 'வாங்கு',
      'te': 'కొనుగోలు',
      'th': 'ซื้อ',
      'tl': 'Bilhin',
      'tr': 'Satın al',
      'uk': 'Купити',
      'ur': 'خریدیں',
      'uz': 'Sotib olish',
      'vi': 'Mua',
      'zh_Hans': '购买',
      'zh_Hant': '購買',
      'zu': 'Thenga',
    },
    'rmad0003': {
      'ko': '구매 복원',
      'af': 'Herstel aankoop',
      'am': 'ግዢን መልስ',
      'ar': 'استعادة الشراء',
      'az': 'Alışı bərpa et',
      'be': 'Аднавіць пакупку',
      'bg': 'Възстанови покупката',
      'bn': 'ক্রয় পুনরুদ্ধার',
      'bs': 'Vrati kupovinu',
      'ca': 'Restaura la compra',
      'cs': 'Obnovit nákup',
      'da': 'Gendan køb',
      'de': 'Kauf wiederherstellen',
      'el': 'Επαναφορά αγοράς',
      'en': 'Restore purchase',
      'es': 'Restaurar compra',
      'et': 'Taasta ost',
      'eu': 'Berreskuratu erosketa',
      'fa': 'بازیابی خرید',
      'fi': 'Palauta osto',
      'fr': 'Restaurer l’achat',
      'gl': 'Restaurar a compra',
      'gu': 'ખરીદી પુનઃસ્થાપિત કરો',
      'he': 'שחזור רכישה',
      'hi': 'खरीद बहाल करें',
      'hr': 'Vrati kupnju',
      'hu': 'Vásárlás visszaállítása',
      'hy': 'Վերականգնել գնումը',
      'id': 'Pulihkan pembelian',
      'is': 'Endurheimta kaup',
      'it': 'Ripristina acquisto',
      'ja': '購入を復元',
      'ka': 'შესყიდვის აღდგენა',
      'kk': 'Сатып алуды қалпына келтіру',
      'km': 'ស្ដារការទិញ',
      'kn': 'ಖರೀದಿ ಮರುಸ್ಥಾಪಿಸಿ',
      'ky': 'Сатып алууну калыбына келтирүү',
      'lo': 'ກູ້ຄືນການຊື້',
      'lt': 'Atkurti pirkinį',
      'lv': 'Atjaunot pirkumu',
      'mk': 'Врати ја купувањето',
      'ml': 'വാങ്ങൽ പുനഃസ്ഥാപിക്കുക',
      'mn': 'Худалдан авалтыг сэргээх',
      'mr': 'खरेदी पुनर्संचयित करा',
      'ms': 'Pulihkan pembelian',
      'my': 'ဝယ်ယူမှု ပြန်လည်ရယူရန်',
      'ne': 'खरिद पुनर्स्थापना',
      'nl': 'Aankoop herstellen',
      'no': 'Gjenopprett kjøp',
      'or': 'କ୍ରୟ ପୁନରୁଦ୍ଧାର କରନ୍ତୁ',
      'pa': 'ਖਰੀਦ ਬਹਾਲ ਕਰੋ',
      'pl': 'Przywróć zakup',
      'ps': 'پیرود بیا راګرځول',
      'pt': 'Restaurar compra',
      'ro': 'Restaurează achiziția',
      'ru': 'Восстановить покупку',
      'sd': 'خريداري بحال ڪريو',
      'si': 'මිලදී ගැනීම නැවත ලබාගන්න',
      'sk': 'Obnoviť nákup',
      'sl': 'Obnovi nakup',
      'sm': 'Toe fa’afo’i le fa’atauga',
      'sq': 'Rikthe blerjen',
      'sr': 'Врати куповину',
      'sv': 'Återställ köp',
      'sw': 'Rejesha ununuzi',
      'ta': 'வாங்கியதை மீட்டமை',
      'te': 'కొనుగోలును పునరుద్ధరించండి',
      'th': 'กู้คืนการซื้อ',
      'tl': 'Ibalik ang binili',
      'tr': 'Satın alımı geri yükle',
      'uk': 'Відновити покупку',
      'ur': 'خریداری بحال کریں',
      'uz': 'Xaridni tiklash',
      'vi': 'Khôi phục giao dịch',
      'zh_Hans': '恢复购买',
      'zh_Hant': '還原購買',
      'zu': 'Buyisela ukuthenga',
    },
    'rmad0004': {
      'ko': '결제 승인을 기다리는 중입니다',
      'af': 'Wag vir betalingsgoedkeuring',
      'am': 'የክፍያ ማጽደቅን በመጠበቅ ላይ',
      'ar': 'في انتظار الموافقة على الدفع',
      'az': 'Ödəniş təsdiqi gözlənilir',
      'be': 'Чаканне пацвярджэння аплаты',
      'bg': 'Изчаква се одобрение на плащането',
      'bn': 'পেমেন্ট অনুমোদনের অপেক্ষায়',
      'bs': 'Čeka se odobrenje plaćanja',
      'ca': 'S\'espera l\'aprovació del pagament',
      'cs': 'Čeká se na schválení platby',
      'da': 'Venter på betalingsgodkendelse',
      'de': 'Warten auf Zahlungsbestätigung',
      'el': 'Αναμονή έγκρισης πληρωμής',
      'en': 'Waiting for payment approval',
      'es': 'Esperando la aprobación del pago',
      'et': 'Ootab makse kinnitust',
      'eu': 'Ordainketa onartzeko zain',
      'fa': 'در انتظار تأیید پرداخت',
      'fi': 'Odotetaan maksun hyväksyntää',
      'fr': 'En attente de la validation du paiement',
      'gl': 'Agardando a aprobación do pagamento',
      'gu': 'ચુકવણી મંજૂરીની રાહ જોઈ રહ્યા છીએ',
      'he': 'ממתין לאישור התשלום',
      'hi': 'भुगतान अनुमोदन की प्रतीक्षा है',
      'hr': 'Čeka se odobrenje plaćanja',
      'hu': 'Várakozás a fizetés jóváhagyására',
      'hy': 'Սպասում է վճարման հաստատմանը',
      'id': 'Menunggu persetujuan pembayaran',
      'is': 'Bíður eftir staðfestingu greiðslu',
      'it': 'In attesa dell’approvazione del pagamento',
      'ja': '支払いの承認を待っています',
      'ka': 'ელოდება გადახდის დადასტურებას',
      'kk': 'Төлемді растау күтілуде',
      'km': 'កំពុងរង់ចាំការអនុម័តការទូទាត់',
      'kn': 'ಪಾವತಿ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
      'ky': 'Төлөм ырастоосу күтүлүүдө',
      'lo': 'ກຳລັງລໍຖ້າການອະນຸມັດການຊຳລະ',
      'lt': 'Laukiama mokėjimo patvirtinimo',
      'lv': 'Gaida maksājuma apstiprinājumu',
      'mk': 'Се чека одобрување на плаќањето',
      'ml': 'പേയ്‌മെന്റ് അംഗീകാരത്തിനായി കാത്തിരിക്കുന്നു',
      'mn': 'Төлбөрийн баталгаажуулалтыг хүлээж байна',
      'mr': 'पेमेंट मंजुरीची प्रतीक्षा आहे',
      'ms': 'Menunggu kelulusan pembayaran',
      'my': 'ငွေပေးချေမှု အတည်ပြုချက်ကို စောင့်နေသည်',
      'ne': 'भुक्तानी स्वीकृतिको प्रतीक्षामा',
      'nl': 'Wachten op betalingsgoedkeuring',
      'no': 'Venter på betalingsgodkjenning',
      'or': 'ଦେୟ ଅନୁମୋଦନ ଅପେକ୍ଷାରେ',
      'pa': 'ਭੁਗਤਾਨ ਮਨਜ਼ੂਰੀ ਦੀ ਉਡੀਕ ਹੈ',
      'pl': 'Oczekiwanie na zatwierdzenie płatności',
      'ps': 'د تادیې تصویب ته سترګې په لار',
      'pt': 'A aguardar aprovação do pagamento',
      'ro': 'Se așteaptă aprobarea plății',
      'ru': 'Ожидается подтверждение оплаты',
      'sd': 'ادائيگي جي منظوري جو انتظار',
      'si': 'ගෙවීම් අනුමැතිය සඳහා රැඳී සිටී',
      'sk': 'Čaká sa na schválenie platby',
      'sl': 'Čakanje na odobritev plačila',
      'sm': 'Fa’atali mo le fa’atagaina o le totogi',
      'sq': 'Në pritje të miratimit të pagesës',
      'sr': 'Чека се одобрење плаћања',
      'sv': 'Väntar på betalningsgodkännande',
      'sw': 'Inasubiri idhini ya malipo',
      'ta': 'கட்டண ஒப்புதலுக்காகக் காத்திருக்கிறது',
      'te': 'చెల్లింపు ఆమోదం కోసం వేచి ఉంది',
      'th': 'กำลังรอการอนุมัติการชำระเงิน',
      'tl': 'Naghihintay ng pag-apruba ng bayad',
      'tr': 'Ödeme onayı bekleniyor',
      'uk': 'Очікується підтвердження оплати',
      'ur': 'ادائیگی کی منظوری کا انتظار ہے',
      'uz': 'To‘lov tasdiqlanishi kutilmoqda',
      'vi': 'Đang chờ duyệt thanh toán',
      'zh_Hans': '正在等待付款确认',
      'zh_Hant': '正在等待付款確認',
      'zu': 'Kulindwe ukuvunywa kwenkokhelo',
    },
    'rmad0005': {
      'ko': '구매를 완료하지 못했습니다',
      'af': 'Aankoop kon nie voltooi word nie',
      'am': 'ግዢው አልተጠናቀቀም',
      'ar': 'تعذّر إتمام عملية الشراء',
      'az': 'Alış tamamlana bilmədi',
      'be': 'Не ўдалося завяршыць пакупку',
      'bg': 'Покупката не можа да бъде завършена',
      'bn': 'ক্রয় সম্পন্ন করা যায়নি',
      'bs': 'Kupovina nije dovršena',
      'ca': 'No s\'ha pogut completar la compra',
      'cs': 'Nákup se nepodařilo dokončit',
      'da': 'Købet kunne ikke gennemføres',
      'de': 'Kauf konnte nicht abgeschlossen werden',
      'el': 'Δεν ήταν δυνατή η ολοκλήρωση της αγοράς',
      'en': 'Purchase could not be completed',
      'es': 'No se pudo completar la compra',
      'et': 'Ostu ei õnnestunud lõpule viia',
      'eu': 'Ezin izan da erosketa osatu',
      'fa': 'خرید کامل نشد',
      'fi': 'Ostoa ei voitu viimeistellä',
      'fr': 'L’achat n’a pas pu être finalisé',
      'gl': 'Non se puido completar a compra',
      'gu': 'ખરીદી પૂર્ણ કરી શકાઈ નથી',
      'he': 'לא ניתן היה להשלים את הרכישה',
      'hi': 'खरीद पूरी नहीं हो सकी',
      'hr': 'Kupnja nije dovršena',
      'hu': 'A vásárlás nem fejeződött be',
      'hy': 'Չհաջողվեց ավարտել գնումը',
      'id': 'Pembelian tidak dapat diselesaikan',
      'is': 'Ekki tókst að ljúka kaupum',
      'it': 'Impossibile completare l’acquisto',
      'ja': '購入を完了できませんでした',
      'ka': 'შესყიდვის დასრულება ვერ მოხერხდა',
      'kk': 'Сатып алу аяқталмады',
      'km': 'មិនអាចបញ្ចប់ការទិញបានទេ',
      'kn': 'ಖರೀದಿ ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ',
      'ky': 'Сатып алуу аяктаган жок',
      'lo': 'ບໍ່ສາມາດເຮັດການຊື້ໃຫ້ສຳເລັດໄດ້',
      'lt': 'Nepavyko užbaigti pirkimo',
      'lv': 'Neizdevās pabeigt pirkumu',
      'mk': 'Купувањето не можеше да се заврши',
      'ml': 'വാങ്ങൽ പൂർത്തിയാക്കാനായില്ല',
      'mn': 'Худалдан авалтыг дуусгаж чадсангүй',
      'mr': 'खरेदी पूर्ण होऊ शकली नाही',
      'ms': 'Pembelian tidak dapat diselesaikan',
      'my': 'ဝယ်ယူမှုကို မပြီးမြောက်နိုင်ပါ',
      'ne': 'खरिद पूरा गर्न सकिएन',
      'nl': 'Aankoop kon niet worden voltooid',
      'no': 'Kjøpet kunne ikke fullføres',
      'or': 'କ୍ରୟ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇପାରିଲା ନାହିଁ',
      'pa': 'ਖਰੀਦ ਪੂਰੀ ਨਹੀਂ ਹੋ ਸਕੀ',
      'pl': 'Nie udało się zrealizować zakupu',
      'ps': 'پیرود بشپړ نه شو',
      'pt': 'Não foi possível concluir a compra',
      'ro': 'Achiziția nu a putut fi finalizată',
      'ru': 'Не удалось завершить покупку',
      'sd': 'خريداري مڪمل نه ٿي سگهي',
      'si': 'මිලදී ගැනීම සම්පූර්ණ කළ නොහැකි විය',
      'sk': 'Nákup sa nepodarilo dokončiť',
      'sl': 'Nakupa ni bilo mogoče dokončati',
      'sm': 'E le’i mafai ona fa’auma le fa’atauga',
      'sq': 'Blerja nuk mund të përfundohej',
      'sr': 'Куповина није завршена',
      'sv': 'Köpet kunde inte slutföras',
      'sw': 'Ununuzi haukukamilika',
      'ta': 'வாங்குதலை நிறைவு செய்ய முடியவில்லை',
      'te': 'కొనుగోలును పూర్తి చేయలేకపోయాం',
      'th': 'ไม่สามารถทำการซื้อให้เสร็จสมบูรณ์ได้',
      'tl': 'Hindi makumpleto ang pagbili',
      'tr': 'Satın alma tamamlanamadı',
      'uk': 'Не вдалося завершити покупку',
      'ur': 'خریداری مکمل نہیں ہو سکی',
      'uz': 'Xaridni yakunlab bo‘lmadi',
      'vi': 'Không thể hoàn tất giao dịch',
      'zh_Hans': '购买未能完成',
      'zh_Hant': '購買未能完成',
      'zu': 'Ukuthenga akuqedwanga',
    },
    'rmad0006': {
      'ko': '구매 내역이 없습니다',
      'af': 'Geen aankoop gevind nie',
      'am': 'ምንም ግዢ አልተገኘም',
      'ar': 'لم يتم العثور على أي عملية شراء',
      'az': 'Alış tapılmadı',
      'be': 'Пакупак не знойдзена',
      'bg': 'Не е намерена покупка',
      'bn': 'কোনো ক্রয় পাওয়া যায়নি',
      'bs': 'Kupovina nije pronađena',
      'ca': 'No s\'ha trobat cap compra',
      'cs': 'Nebyl nalezen žádný nákup',
      'da': 'Intet køb fundet',
      'de': 'Kein Kauf gefunden',
      'el': 'Δεν βρέθηκε αγορά',
      'en': 'No purchase found',
      'es': 'No se encontró ninguna compra',
      'et': 'Ostu ei leitud',
      'eu': 'Ez da erosketarik aurkitu',
      'fa': 'خریدی یافت نشد',
      'fi': 'Ostoa ei löytynyt',
      'fr': 'Aucun achat trouvé',
      'gl': 'Non se atopou ningunha compra',
      'gu': 'કોઈ ખરીદી મળી નથી',
      'he': 'לא נמצאה רכישה',
      'hi': 'कोई खरीद नहीं मिली',
      'hr': 'Kupnja nije pronađena',
      'hu': 'Nem található vásárlás',
      'hy': 'Գնում չի գտնվել',
      'id': 'Pembelian tidak ditemukan',
      'is': 'Engin kaup fundust',
      'it': 'Nessun acquisto trovato',
      'ja': '購入履歴が見つかりません',
      'ka': 'შესყიდვა ვერ მოიძებნა',
      'kk': 'Сатып алу табылмады',
      'km': 'រកមិនឃើញការទិញទេ',
      'kn': 'ಯಾವುದೇ ಖರೀದಿ ಕಂಡುಬಂದಿಲ್ಲ',
      'ky': 'Сатып алуу табылган жок',
      'lo': 'ບໍ່ພົບການຊື້',
      'lt': 'Pirkimų nerasta',
      'lv': 'Pirkums nav atrasts',
      'mk': 'Не е пронајдено купување',
      'ml': 'വാങ്ങൽ ഒന്നും കണ്ടെത്തിയില്ല',
      'mn': 'Худалдан авалт олдсонгүй',
      'mr': 'कोणतीही खरेदी सापडली नाही',
      'ms': 'Tiada pembelian ditemui',
      'my': 'ဝယ်ယူမှု မတွေ့ပါ',
      'ne': 'कुनै खरिद भेटिएन',
      'nl': 'Geen aankoop gevonden',
      'no': 'Fant ingen kjøp',
      'or': 'କୌଣସି କ୍ରୟ ମିଳିଲା ନାହିଁ',
      'pa': 'ਕੋਈ ਖਰੀਦ ਨਹੀਂ ਮਿਲੀ',
      'pl': 'Nie znaleziono zakupu',
      'ps': 'هیڅ پیرود ونه موندل شو',
      'pt': 'Nenhuma compra encontrada',
      'ro': 'Nu s-a găsit nicio achiziție',
      'ru': 'Покупка не найдена',
      'sd': 'ڪا خريداري نه ملي',
      'si': 'මිලදී ගැනීමක් හමු නොවීය',
      'sk': 'Nenašiel sa žiadny nákup',
      'sl': 'Nakupa ni bilo mogoče najti',
      'sm': 'E leai se fa’atauga na maua',
      'sq': 'Nuk u gjet asnjë blerje',
      'sr': 'Куповина није пронађена',
      'sv': 'Inget köp hittades',
      'sw': 'Hakuna ununuzi uliopatikana',
      'ta': 'வாங்கிய பதிவு எதுவும் இல்லை',
      'te': 'ఏ కొనుగోలు కనుగొనబడలేదు',
      'th': 'ไม่พบการซื้อ',
      'tl': 'Walang nakitang binili',
      'tr': 'Satın alma bulunamadı',
      'uk': 'Покупок не знайдено',
      'ur': 'کوئی خریداری نہیں ملی',
      'uz': 'Xarid topilmadi',
      'vi': 'Không tìm thấy giao dịch',
      'zh_Hans': '未找到购买记录',
      'zh_Hant': '未找到購買紀錄',
      'zu': 'Akukho ukuthenga okutholakele',
    },
    'rmad0007': {
      'ko': '한 번만 구매하면 광고가 영구히 사라집니다.',
      'af': 'Een keer koop verwyder advertensies vir altyd.',
      'am': 'አንድ ጊዜ ከገዙ ማስታወቂያዎች ለዘላለም ይጠፋሉ።',
      'ar': 'عملية شراء واحدة تزيل الإعلانات نهائيًا.',
      'az': 'Bir dəfə alsanız, reklamlar həmişəlik yox olur.',
      'be': 'Адна пакупка — і рэклама знікае назаўсёды.',
      'bg': 'Еднократна покупка премахва рекламите завинаги.',
      'bn': 'একবার কিনলেই বিজ্ঞাপন চিরতরে চলে যাবে।',
      'bs': 'Jedna kupovina trajno uklanja reklame.',
      'ca': 'Una sola compra elimina els anuncis per sempre.',
      'cs': 'Jediný nákup odstraní reklamy navždy.',
      'da': 'Ét køb fjerner annoncer for altid.',
      'de': 'Ein einmaliger Kauf entfernt die Werbung dauerhaft.',
      'el': 'Μία αγορά αφαιρεί τις διαφημίσεις για πάντα.',
      'en': 'A single purchase removes ads forever.',
      'es': 'Una sola compra elimina los anuncios para siempre.',
      'et': 'Üks ost eemaldab reklaamid jäädavalt.',
      'eu': 'Erosketa bakar batek iragarkiak betiko kentzen ditu.',
      'fa': 'یک بار خرید، تبلیغات را برای همیشه حذف می‌کند.',
      'fi': 'Yksi osto poistaa mainokset pysyvästi.',
      'fr': 'Un seul achat supprime les publicités définitivement.',
      'gl': 'Unha soa compra elimina os anuncios para sempre.',
      'gu': 'એક જ ખરીદીથી જાહેરાતો કાયમ માટે દૂર થાય છે.',
      'he': 'רכישה אחת מסירה את הפרסומות לצמיתות.',
      'hi': 'एक बार खरीदने पर विज्ञापन हमेशा के लिए हट जाते हैं।',
      'hr': 'Jedna kupnja trajno uklanja oglase.',
      'hu': 'Egyetlen vásárlás véglegesen eltávolítja a hirdetéseket.',
      'hy': 'Մեկ գնումը ընդմիշտ հեռացնում է գովազդը։',
      'id': 'Sekali beli, iklan hilang selamanya.',
      'is': 'Ein kaup fjarlægja auglýsingar að eilífu.',
      'it': 'Un solo acquisto rimuove la pubblicità per sempre.',
      'ja': '一度の購入で広告が永久に消えます。',
      'ka': 'ერთი შესყიდვა სამუდამოდ შლის რეკლამას.',
      'kk': 'Бір рет сатып алсаңыз, жарнама мәңгілікке жойылады.',
      'km': 'ការទិញតែម្ដងលុបការផ្សាយពាណិជ្ជកម្មជារៀងរហូត។',
      'kn': 'ಒಂದೇ ಖರೀದಿಯಿಂದ ಜಾಹೀರಾತುಗಳು ಶಾಶ್ವತವಾಗಿ ಮಾಯವಾಗುತ್ತವೆ.',
      'ky': 'Бир жолу сатып алсаңыз, жарнама түбөлүккө жоголот.',
      'lo': 'ຊື້ເທື່ອດຽວ ໂຄສະນາຫາຍໄປຕະຫຼອດ.',
      'lt': 'Vienas pirkimas pašalina skelbimus visam laikui.',
      'lv': 'Viens pirkums neatgriezeniski noņem reklāmas.',
      'mk': 'Едно купување трајно ги отстранува рекламите.',
      'ml': 'ഒരൊറ്റ വാങ്ങലിൽ പരസ്യങ്ങൾ എന്നേക്കുമായി മാറും.',
      'mn': 'Нэг удаа худалдан авахад сурталчилгаа үүрд алга болно.',
      'mr': 'एकदा खरेदी केल्यास जाहिराती कायमच्या नाहीशा होतात.',
      'ms': 'Sekali beli, iklan hilang selama-lamanya.',
      'my': 'တစ်ကြိမ်ဝယ်ယူလျှင် ကြော်ငြာများ အမြဲတမ်း ပျောက်သွားပါမည်။',
      'ne': 'एक पटक किन्नुभयो भने विज्ञापन सधैंका लागि हट्छ।',
      'nl': 'Eén aankoop verwijdert advertenties voorgoed.',
      'no': 'Ett kjøp fjerner annonser for godt.',
      'or': 'ଥରେ କିଣିଲେ ବିଜ୍ଞାପନ ସବୁଦିନ ପାଇଁ ଚାଲିଯିବ।',
      'pa': 'ਇੱਕ ਵਾਰ ਖਰੀਦਣ ਨਾਲ ਇਸ਼ਤਿਹਾਰ ਹਮੇਸ਼ਾ ਲਈ ਹਟ ਜਾਂਦੇ ਹਨ।',
      'pl': 'Jeden zakup usuwa reklamy na zawsze.',
      'ps': 'یو ځل پیرود اعلانونه د تل لپاره لرې کوي.',
      'pt': 'Uma única compra remove os anúncios para sempre.',
      'ro': 'O singură achiziție elimină reclamele pentru totdeauna.',
      'ru': 'Одна покупка убирает рекламу навсегда.',
      'sd': 'هڪ ڀيرو خريد ڪرڻ سان اشتهار هميشه لاءِ ختم ٿي ويندا.',
      'si': 'එක් මිලදී ගැනීමකින් දැන්වීම් සදහටම ඉවත් වේ.',
      'sk': 'Jediný nákup odstráni reklamy navždy.',
      'sl': 'En sam nakup trajno odstrani oglase.',
      'sm': 'E tasi le fa’atauga e mou atu ai fa’asalalauga e fa’avavau.',
      'sq': 'Një blerje e vetme i heq reklamat përgjithmonë.',
      'sr': 'Једна куповина трајно уклања огласе.',
      'sv': 'Ett köp tar bort annonser för alltid.',
      'sw': 'Ununuzi mmoja huondoa matangazo milele.',
      'ta': 'ஒரே வாங்குதலில் விளம்பரங்கள் நிரந்தரமாக நீங்கும்.',
      'te': 'ఒక్కసారి కొంటే ప్రకటనలు శాశ్వతంగా తొలగిపోతాయి.',
      'th': 'ซื้อครั้งเดียว โฆษณาหายไปตลอดกาล',
      'tl': 'Isang beses lang bumili, tuluyan nang mawawala ang mga ad.',
      'tr': 'Tek seferlik satın alma reklamları kalıcı olarak kaldırır.',
      'uk': 'Одна покупка прибирає рекламу назавжди.',
      'ur': 'ایک بار خریدنے پر اشتہارات ہمیشہ کے لیے ختم ہو جاتے ہیں۔',
      'uz': 'Bir marta sotib olsangiz, reklama butunlay yo‘qoladi.',
      'vi': 'Chỉ cần mua một lần, quảng cáo biến mất vĩnh viễn.',
      'zh_Hans': '一次购买，永久去除广告。',
      'zh_Hant': '一次購買，永久移除廣告。',
      'zu': 'Ukuthenga kanye kususa izikhangiso unomphela.',
    },
    'rmad0008': {
      'ko': '광고 제거',
      'af': 'Verwyder advertensies',
      'am': 'ማስታወቂያ አስወግድ',
      'ar': 'إزالة الإعلانات',
      'az': 'Reklamı sil',
      'be': 'Прыбраць рэкламу',
      'bg': 'Без реклами',
      'bn': 'বিজ্ঞাপন সরান',
      'bs': 'Ukloni reklame',
      'ca': 'Treu anuncis',
      'cs': 'Odebrat reklamy',
      'da': 'Fjern annoncer',
      'de': 'Werbung entfernen',
      'el': 'Χωρίς διαφημίσεις',
      'en': 'Remove ads',
      'es': 'Quitar anuncios',
      'et': 'Eemalda reklaamid',
      'eu': 'Kendu iragarkiak',
      'fa': 'حذف تبلیغات',
      'fi': 'Poista mainokset',
      'fr': 'Sans publicité',
      'gl': 'Quitar anuncios',
      'gu': 'જાહેરાત દૂર કરો',
      'he': 'ללא פרסומות',
      'hi': 'विज्ञापन हटाएं',
      'hr': 'Ukloni oglase',
      'hu': 'Hirdetések nélkül',
      'hy': 'Հեռացնել գովազդը',
      'id': 'Hapus iklan',
      'is': 'Fjarlægja auglýsingar',
      'it': 'Rimuovi pubblicità',
      'ja': '広告を消す',
      'ka': 'რეკლამის მოხსნა',
      'kk': 'Жарнаманы өшіру',
      'km': 'លុបការផ្សាយ',
      'kn': 'ಜಾಹೀರಾತು ತೆಗೆಯಿರಿ',
      'ky': 'Жарнаманы өчүрүү',
      'lo': 'ລຶບໂຄສະນາ',
      'lt': 'Pašalinti skelbimus',
      'lv': 'Noņemt reklāmas',
      'mk': 'Отстрани реклами',
      'ml': 'പരസ്യം നീക്കുക',
      'mn': 'Сурталчилгаа арилгах',
      'mr': 'जाहिराती काढा',
      'ms': 'Buang iklan',
      'my': 'ကြော်ငြာ ဖယ်ရန်',
      'ne': 'विज्ञापन हटाउनुहोस्',
      'nl': 'Advertenties weg',
      'no': 'Fjern annonser',
      'or': 'ବିଜ୍ଞାପନ ହଟାନ୍ତୁ',
      'pa': 'ਇਸ਼ਤਿਹਾਰ ਹਟਾਓ',
      'pl': 'Usuń reklamy',
      'ps': 'اعلانونه لرې کړئ',
      'pt': 'Remover anúncios',
      'ro': 'Fără reclame',
      'ru': 'Убрать рекламу',
      'sd': 'اشتهار هٽايو',
      'si': 'දැන්වීම් ඉවත් කරන්න',
      'sk': 'Odstrániť reklamy',
      'sl': 'Odstrani oglase',
      'sm': 'Aveese fa’asalalauga',
      'sq': 'Hiq reklamat',
      'sr': 'Уклони огласе',
      'sv': 'Ta bort annonser',
      'sw': 'Ondoa matangazo',
      'ta': 'விளம்பரம் நீக்கு',
      'te': 'ప్రకటనలు తొలగించు',
      'th': 'ลบโฆษณา',
      'tl': 'Alisin ang mga ad',
      'tr': 'Reklamları kaldır',
      'uk': 'Прибрати рекламу',
      'ur': 'اشتہارات ہٹائیں',
      'uz': 'Reklamani olib tashlash',
      'vi': 'Bỏ quảng cáo',
      'zh_Hans': '去除广告',
      'zh_Hant': '移除廣告',
      'zu': 'Susa izikhangiso',
    },
    'rmad0009': {
      'ko': '광고가 제거되었습니다',
      'af': 'Advertensies is verwyder',
      'am': 'ማስታወቂያዎች ተወግደዋል',
      'ar': 'تمت إزالة الإعلانات',
      'az': 'Reklamlar silindi',
      'be': 'Рэклама прыбрана',
      'bg': 'Рекламите са премахнати',
      'bn': 'বিজ্ঞাপন সরানো হয়েছে',
      'bs': 'Reklame su uklonjene',
      'ca': 'S\'han tret els anuncis',
      'cs': 'Reklamy byly odebrány',
      'da': 'Annoncer er fjernet',
      'de': 'Werbung wurde entfernt',
      'el': 'Οι διαφημίσεις αφαιρέθηκαν',
      'en': 'Ads removed',
      'es': 'Se han quitado los anuncios',
      'et': 'Reklaamid on eemaldatud',
      'eu': 'Iragarkiak kendu dira',
      'fa': 'تبلیغات حذف شد',
      'fi': 'Mainokset poistettu',
      'fr': 'Publicités supprimées',
      'gl': 'Quitáronse os anuncios',
      'gu': 'જાહેરાતો દૂર કરવામાં આવી',
      'he': 'הפרסומות הוסרו',
      'hi': 'विज्ञापन हटा दिए गए',
      'hr': 'Oglasi su uklonjeni',
      'hu': 'A hirdetések eltávolítva',
      'hy': 'Գովազդը հեռացվեց',
      'id': 'Iklan telah dihapus',
      'is': 'Auglýsingar fjarlægðar',
      'it': 'Pubblicità rimossa',
      'ja': '広告を削除しました',
      'ka': 'რეკლამა წაიშალა',
      'kk': 'Жарнама өшірілді',
      'km': 'បានលុបការផ្សាយពាណិជ្ជកម្ម',
      'kn': 'ಜಾಹೀರಾತುಗಳನ್ನು ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
      'ky': 'Жарнама өчүрүлдү',
      'lo': 'ລຶບໂຄສະນາແລ້ວ',
      'lt': 'Skelbimai pašalinti',
      'lv': 'Reklāmas ir noņemtas',
      'mk': 'Рекламите се отстранети',
      'ml': 'പരസ്യങ്ങൾ നീക്കി',
      'mn': 'Сурталчилгааг арилгалаа',
      'mr': 'जाहिराती काढल्या',
      'ms': 'Iklan telah dibuang',
      'my': 'ကြော်ငြာများကို ဖယ်ရှားပြီးပါပြီ',
      'ne': 'विज्ञापन हटाइयो',
      'nl': 'Advertenties verwijderd',
      'no': 'Annonser er fjernet',
      'or': 'ବିଜ୍ଞାପନ ହଟାଯାଇଛି',
      'pa': 'ਇਸ਼ਤਿਹਾਰ ਹਟਾ ਦਿੱਤੇ ਗਏ',
      'pl': 'Reklamy usunięte',
      'ps': 'اعلانونه لرې شول',
      'pt': 'Anúncios removidos',
      'ro': 'Reclamele au fost eliminate',
      'ru': 'Реклама удалена',
      'sd': 'اشتهار هٽائي ڇڏيا ويا',
      'si': 'දැන්වීම් ඉවත් කරන ලදී',
      'sk': 'Reklamy boli odstránené',
      'sl': 'Oglasi so odstranjeni',
      'sm': 'Ua aveesea fa’asalalauga',
      'sq': 'Reklamat u hoqën',
      'sr': 'Огласи су уклоњени',
      'sv': 'Annonser borttagna',
      'sw': 'Matangazo yameondolewa',
      'ta': 'விளம்பரங்கள் நீக்கப்பட்டன',
      'te': 'ప్రకటనలు తొలగించబడ్డాయి',
      'th': 'ลบโฆษณาแล้ว',
      'tl': 'Naalis na ang mga ad',
      'tr': 'Reklamlar kaldırıldı',
      'uk': 'Рекламу видалено',
      'ur': 'اشتہارات ہٹا دیے گئے',
      'uz': 'Reklama olib tashlandi',
      'vi': 'Đã gỡ quảng cáo',
      'zh_Hans': '已去除广告',
      'zh_Hant': '已移除廣告',
      'zu': 'Izikhangiso zisusiwe',
    },
    'c0ob4q61': {
      'ko': '꺼짐',
      'af': 'Af',
      'am': 'ጠፍቷል',
      'ar': 'عن',
      'az': 'Söndür',
      'be': 'Выключана',
      'bg': 'Изключено',
      'bn': 'বন্ধ',
      'bs': 'Isključeno',
      'ca': 'Desactivat',
      'cs': 'Vypnuto',
      'da': 'Slukket',
      'de': 'Aus',
      'el': 'Μακριά από',
      'en': 'Off',
      'es': 'Apagado',
      'et': 'Väljas',
      'eu': 'Itzalita',
      'fa': 'خاموش',
      'fi': 'Pois',
      'fr': 'Désactivé',
      'gl': 'Desactivado',
      'gu': 'બંધ',
      'he': 'כבוי',
      'hi': 'बंद',
      'hr': 'Isključeno',
      'hu': 'Le',
      'hy': 'Անջատված',
      'id': 'Mati',
      'is': 'Slökkt',
      'it': 'Spento',
      'ja': 'オフ',
      'ka': 'გამორთულია',
      'kk': 'Өшірулі',
      'km': 'បិទ',
      'kn': 'ಆಫ್',
      'ky': 'Өчүк',
      'lo': 'ປິດ',
      'lt': 'Išjungta',
      'lv': 'Izslēgts',
      'mk': 'Исклучено',
      'ml': 'ഓഫ്',
      'mn': 'Унтраах',
      'mr': 'बंद',
      'ms': 'Mati',
      'my': 'ပိတ်သည်။',
      'ne': 'बन्द',
      'nl': 'Uit',
      'no': 'Av',
      'or': 'ବନ୍ଦ ଅଛି',
      'pa': 'ਬੰਦ',
      'pl': 'Wyłączony',
      'ps': 'بند',
      'pt': 'Desligado',
      'ro': 'Dezactivat',
      'ru': 'Выключенный',
      'sd': 'بند',
      'si': 'අක්‍රියයි',
      'sk': 'Vypnuté',
      'sl': 'Izklopljeno',
      'sm': 'Tape',
      'sq': 'Joaktiv',
      'sr': 'Искључено',
      'sv': 'Av',
      'sw': 'Imezimwa',
      'ta': 'ஆஃப்',
      'te': 'ఆఫ్',
      'th': 'ปิด',
      'tl': 'Naka-off',
      'tr': 'Kapalı',
      'uk': 'Вимкнено',
      'ur': 'آف',
      'uz': 'Oʻchirilgan',
      'vi': 'Tắt',
      'zh_Hans': '离开',
      'zh_Hant': '離開',
      'zu': 'Valiwe',
    },
    '24qab3qx': {
      'ko': '켜짐',
      'af': 'Aan',
      'am': 'በርቷል',
      'ar': 'على',
      'az': 'Aktiv',
      'be': 'Уключана',
      'bg': 'Включено',
      'bn': 'চালু',
      'bs': 'Uključeno',
      'ca': 'Activat',
      'cs': 'Na',
      'da': 'På',
      'de': 'An',
      'el': 'Επί',
      'en': 'On',
      'es': 'En',
      'et': 'Sees',
      'eu': 'Piztuta',
      'fa': 'روشن',
      'fi': 'Päällä',
      'fr': 'Sur',
      'gl': 'Activado',
      'gu': 'ચાલુ',
      'he': 'עַל',
      'hi': 'पर',
      'hr': 'Na',
      'hu': 'On',
      'hy': 'Միացված է',
      'id': 'Pada',
      'is': 'Kveikt',
      'it': 'SU',
      'ja': '点灯',
      'ka': 'ჩართულია',
      'kk': 'Қосулы',
      'km': 'បើក',
      'kn': 'ಆನ್',
      'ky': 'Күйүк',
      'lo': 'ສຸດ',
      'lt': 'Įjungta',
      'lv': 'Ieslēgts',
      'mk': 'Вклучено',
      'ml': 'ഓൺ',
      'mn': 'Асаалттай',
      'mr': 'चालू',
      'ms': 'hidup',
      'my': 'ဂရန်',
      'ne': 'खुल्ला',
      'nl': 'Op',
      'no': 'På',
      'or': 'ଅନ୍',
      'pa': 'ਚਾਲੂ',
      'pl': 'NA',
      'ps': 'په',
      'pt': 'Sobre',
      'ro': 'Pe',
      'ru': 'На',
      'sd': 'تي',
      'si': 'ක්‍රියාත්මකයි',
      'sk': 'Zapnuté',
      'sl': 'Vklopljeno',
      'sm': 'luga',
      'sq': 'Aktiv',
      'sr': 'Укључено',
      'sv': 'På',
      'sw': 'Washa',
      'ta': 'அன்று',
      'te': 'ఆన్',
      'th': 'บน',
      'tl': 'Naka-on',
      'tr': 'Açık',
      'uk': 'Увімкнено',
      'ur': 'پر',
      'uz': 'Yoniq',
      'vi': 'TRÊN',
      'zh_Hans': '在',
      'zh_Hant': '在',
      'zu': 'Vuliwe',
    },
    'iq5z1i00': {
      'ko': '손전등',
      'af': 'Flitslig',
      'am': 'የእጅ ባትሪ',
      'ar': 'مصباح يدوي',
      'az': 'Fənər',
      'be': 'Ліхтарык',
      'bg': 'Фенерче',
      'bn': 'টর্চলাইট',
      'bs': 'Svjetiljka',
      'ca': 'Llanterna',
      'cs': 'Svítilna',
      'da': 'Lommelygte',
      'de': 'Taschenlampe',
      'el': 'Φακός',
      'en': 'Flashlight',
      'es': 'Flash',
      'et': 'Taskulamp',
      'eu': 'Linterna',
      'fa': 'چراغ قوه',
      'fi': 'Taskulamppu',
      'fr': 'Lampe de poche',
      'gl': 'Lanterna',
      'gu': 'ફ્લેશલાઇટ',
      'he': 'פָּנַס כִּיס',
      'hi': 'टॉर्च',
      'hr': 'Svjetiljka',
      'hu': 'Zseblámpa',
      'hy': 'Լապտեր',
      'id': 'Senter',
      'is': 'Vasaljós',
      'it': 'Torcia elettrica',
      'ja': '懐中電灯',
      'ka': 'ფანარი',
      'kk': 'Фонар',
      'km': 'ពិល',
      'kn': 'ಫ್ಲ್ಯಾಶ್‌ಲೈಟ್',
      'ky': 'Кол чырак',
      'lo': 'ໄຟສາຍ',
      'lt': 'Žibintuvėlis',
      'lv': 'Lukturītis',
      'mk': 'Фенерче',
      'ml': 'ഫ്ലാഷ്‌ലൈറ്റ്',
      'mn': 'Гар чийдэн',
      'mr': 'टॉर्च',
      'ms': 'Lampu suluh',
      'my': 'ဓာတ်မီး',
      'ne': 'टर्चलाइट',
      'nl': 'Zaklamp',
      'no': 'Lommelykt',
      'or': 'ଫ୍ଲାସଲାଇଟ୍',
      'pa': 'ਫਲੈਸ਼ਲਾਈਟ',
      'pl': 'Flesz',
      'ps': 'لاسي څراغ',
      'pt': 'Lanterna',
      'ro': 'Lanternă',
      'ru': 'Фонарик',
      'sd': 'ٽارچ',
      'si': 'ෆ්ලෑෂ් ලයිට්',
      'sk': 'Baterka',
      'sl': 'Svetilka',
      'sm': 'moliuila',
      'sq': 'Fener',
      'sr': 'Батеријска лампа',
      'sv': 'Ficklampa',
      'sw': 'Tochi',
      'ta': 'பிரகாச ஒளி',
      'te': 'ఫ్లాష్‌లైట్',
      'th': 'ไฟฉาย',
      'tl': 'Flashlight',
      'tr': 'El feneri',
      'uk': 'Ліхтарик',
      'ur': 'ٹارچ',
      'uz': 'Chiroq',
      'vi': 'Đèn pin',
      'zh_Hans': '手电筒',
      'zh_Hant': '手電筒',
      'zu': 'Ithoshi',
    },
    'pumtmx3a': {
      'ko': '홈',
      'af': 'huis',
      'am': 'ቤት',
      'ar': 'بيت',
      'az': 'ev',
      'be': 'дом',
      'bg': 'дом',
      'bn': 'বাড়ি',
      'bs': 'dom',
      'ca': 'casa',
      'cs': 'domov',
      'da': 'hjem',
      'de': 'heim',
      'el': 'σπίτι',
      'en': 'home',
      'es': 'hogar',
      'et': 'kodu',
      'eu': 'etxea',
      'fa': 'خانه',
      'fi': 'kotiin',
      'fr': 'maison',
      'gl': 'fogar',
      'gu': 'ઘર',
      'he': 'בַּיִת',
      'hi': 'घर',
      'hr': 'dom',
      'hu': 'otthon',
      'hy': 'տուն',
      'id': 'rumah',
      'is': 'heim',
      'it': 'casa',
      'ja': 'ホーム',
      'ka': 'სახლი',
      'kk': 'үй',
      'km': 'ផ្ទះ',
      'kn': 'ಮನೆ',
      'ky': 'үй',
      'lo': 'ບ້ານ',
      'lt': 'namai',
      'lv': 'mājas',
      'mk': 'дом',
      'ml': 'വീട്',
      'mn': 'гэр',
      'mr': 'घर',
      'ms': 'rumah',
      'my': 'အိမ်',
      'ne': 'घर',
      'nl': 'thuis',
      'no': 'hjem',
      'or': 'ଘର',
      'pa': 'ਘਰ',
      'pl': 'dom',
      'ps': 'کور',
      'pt': 'lar',
      'ro': 'acasă',
      'ru': 'дом',
      'sd': 'گھر',
      'si': 'නිවස',
      'sk': 'domov',
      'sl': 'dom',
      'sm': 'aiga',
      'sq': 'shtëpi',
      'sr': 'дом',
      'sv': 'hem',
      'sw': 'nyumbani',
      'ta': 'வீடு',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tl': 'bahay',
      'tr': 'Ev',
      'uk': 'дім',
      'ur': 'گھر',
      'uz': 'uy',
      'vi': 'trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
      'zu': 'ekhaya',
    },
    'n4v8t2q6': {
      'ko': '이 기기는 플래시가 없어 화면을 밝힙니다',
      'af': 'Hierdie toestel het geen flits nie, daarom word die skerm verhelder',
      'am': 'ይህ መሣሪያ ብልጭታ የለውም፤ ስለዚህ ማያ ገጹ ይበራል',
      'ar': 'لا يحتوي هذا الجهاز على فلاش، لذا تتم إضاءة الشاشة',
      'az': 'Bu cihazda flaş yoxdur, ona görə ekran işıqlandırılır',
      'be': 'На гэтай прыладзе няма ўспышкі, таму падсвятляецца экран',
      'bg': 'Това устройство няма светкавица, затова екранът се осветява',
      'bn': 'এই ডিভাইসে ফ্ল্যাশ নেই, তাই স্ক্রিন উজ্জ্বল করা হচ্ছে',
      'bs': 'Ovaj uređaj nema bljeskalicu, pa se osvjetljava ekran',
      'ca': 'Aquest dispositiu no té flaix, així que s’il·lumina la pantalla',
      'cs': 'Toto zařízení nemá blesk, proto se rozsvítí obrazovka',
      'da': 'Denne enhed har ingen blitz, så skærmen lyser op',
      'de': 'Dieses Gerät hat kein Blitzlicht, daher wird der Bildschirm aufgehellt',
      'el': 'Αυτή η συσκευή δεν έχει φλας, γι’ αυτό φωτίζεται η οθόνη',
      'en': 'This device has no flash, so the screen is used as the light',
      'es': 'Este dispositivo no tiene flash, por lo que se ilumina la pantalla',
      'et': 'Sellel seadmel pole välku, seetõttu valgustatakse ekraani',
      'eu': 'Gailu honek ez du flashik, beraz pantaila argitzen da',
      'fa': 'این دستگاه فلش ندارد، بنابراین صفحه روشن می‌شود',
      'fi': 'Tässä laitteessa ei ole salamaa, joten näyttö kirkastetaan',
      'fr': 'Cet appareil n’a pas de flash, l’écran sert donc de lampe',
      'gl': 'Este dispositivo non ten flash, así que se ilumina a pantalla',
      'gu': 'આ ઉપકરણમાં ફ્લેશ નથી, તેથી સ્ક્રીન પ્રકાશિત કરવામાં આવે છે',
      'he': 'במכשיר זה אין פלאש, ולכן המסך מואר',
      'hi': 'इस डिवाइस में फ़्लैश नहीं है, इसलिए स्क्रीन को रोशन किया जाता है',
      'hr': 'Ovaj uređaj nema bljeskalicu pa se osvjetljava zaslon',
      'hu': 'Ezen az eszközön nincs vaku, ezért a képernyő világít',
      'hy': 'Այս սարքը լապտեր չունի, ուստի լուսավորվում է էկրանը',
      'id': 'Perangkat ini tidak memiliki lampu kilat, jadi layar yang dinyalakan',
      'is': 'Þetta tæki er ekki með flass, því lýsist skjárinn upp',
      'it': 'Questo dispositivo non ha il flash, quindi viene illuminato lo schermo',
      'ja': 'この端末にはフラッシュがないため、画面を明るくします',
      'ka': 'ამ მოწყობილობას ფლეში არ აქვს, ამიტომ ნათდება ეკრანი',
      'kk': 'Бұл құрылғыда жарқылдақ жоқ, сондықтан экран жарықтандырылады',
      'km': 'ឧបករណ៍នេះមិនមានពន្លឺហ្វ្លាស់ទេ ដូច្នេះអេក្រង់ត្រូវបានបំភ្លឺ',
      'kn': 'ಈ ಸಾಧನದಲ್ಲಿ ಫ್ಲ್ಯಾಶ್ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಪರದೆಯನ್ನು ಬೆಳಗಿಸಲಾಗುತ್ತದೆ',
      'ky': 'Бул түзмөктө жарык жок, ошондуктан экран жарыктандырылат',
      'lo': 'ອຸປະກອນນີ້ບໍ່ມີແຟລດ ດັ່ງນັ້ນຈຶ່ງເປີດແສງໜ້າຈໍແທນ',
      'lt': 'Šiame įrenginyje nėra blykstės, todėl apšviečiamas ekranas',
      'lv': 'Šai ierīcei nav zibspuldzes, tāpēc tiek izgaismots ekrāns',
      'mk': 'Овој уред нема блиц, затоа се осветлува екранот',
      'ml': 'ഈ ഉപകരണത്തിൽ ഫ്ലാഷ് ഇല്ല, അതിനാൽ സ്ക്രീൻ പ്രകാശിപ്പിക്കുന്നു',
      'mn': 'Энэ төхөөрөмжид гэрэлтүүлэг байхгүй тул дэлгэцийг гэрэлтүүлнэ',
      'mr': 'या डिव्हाइसमध्ये फ्लॅश नाही, म्हणून स्क्रीन उजळवली जाते',
      'ms': 'Peranti ini tiada lampu denyar, jadi skrin dicerahkan',
      'my': 'ဤစက်တွင် ဖလက်ရှ်မရှိသဖြင့် ဖန်သားပြင်ကို လင်းစေပါသည်',
      'ne': 'यो यन्त्रमा फ्ल्यास छैन, त्यसैले स्क्रिन उज्यालो पारिन्छ',
      'nl': 'Dit apparaat heeft geen flitser, daarom wordt het scherm verlicht',
      'no': 'Denne enheten har ingen blits, så skjermen lyser opp',
      'or': 'ଏହି ଡିଭାଇସରେ ଫ୍ଲାସ୍ ନାହିଁ, ତେଣୁ ସ୍କ୍ରିନ୍ ଆଲୋକିତ ହୁଏ',
      'pa': 'ਇਸ ਡੀਵਾਈਸ ਵਿੱਚ ਫਲੈਸ਼ ਨਹੀਂ ਹੈ, ਇਸ ਲਈ ਸਕ੍ਰੀਨ ਨੂੰ ਰੌਸ਼ਨ ਕੀਤਾ ਜਾਂਦਾ ਹੈ',
      'pl': 'To urządzenie nie ma lampy błyskowej, dlatego rozjaśniany jest ekran',
      'ps': 'دا وسیله فلش نه لري، نو سکرین روښانه کیږي',
      'pt': 'Este dispositivo não tem flash, então a tela é iluminada',
      'ro': 'Acest dispozitiv nu are bliț, așa că este luminat ecranul',
      'ru': 'На этом устройстве нет вспышки, поэтому подсвечивается экран',
      'sd': 'هن ڊوائيس ۾ فليش ناهي، تنهنڪري اسڪرين روشن ڪئي وڃي ٿي',
      'si': 'මෙම උපාංගයේ ෆ්ලෑෂ් නොමැති නිසා තිරය දීප්තිමත් කෙරේ',
      'sk': 'Toto zariadenie nemá blesk, preto sa rozsvieti obrazovka',
      'sl': 'Ta naprava nima bliskavice, zato se osvetli zaslon',
      'sm': 'E leai se moli o lenei masini, o lea e faamalamalamaina ai le lau',
      'sq': 'Kjo pajisje nuk ka blic, prandaj ndriçohet ekrani',
      'sr': 'Овај уређај нема блиц, па се осветљава екран',
      'sv': 'Den här enheten har ingen blixt, så skärmen lyses upp',
      'sw': 'Kifaa hiki hakina mweko, kwa hivyo skrini huwashwa',
      'ta': 'இந்தச் சாதனத்தில் ஃபிளாஷ் இல்லை, எனவே திரை ஒளிரச் செய்யப்படுகிறது',
      'te': 'ఈ పరికరంలో ఫ్లాష్ లేదు, కాబట్టి స్క్రీన్ ప్రకాశవంతం చేయబడుతుంది',
      'th': 'อุปกรณ์นี้ไม่มีแฟลช จึงใช้หน้าจอส่องสว่างแทน',
      'tl': 'Walang flash ang device na ito, kaya ang screen ang pinapaliwanag',
      'tr': 'Bu cihazda flaş yok, bu yüzden ekran aydınlatılıyor',
      'uk': 'На цьому пристрої немає спалаху, тому підсвічується екран',
      'ur': 'اس ڈیوائس میں فلیش نہیں ہے، اس لیے اسکرین کو روشن کیا جاتا ہے',
      'uz': 'Bu qurilmada chaqnoq yo‘q, shuning uchun ekran yoritiladi',
      'vi': 'Thiết bị này không có đèn flash nên màn hình được làm sáng',
      'zh_Hans': '此设备没有闪光灯，因此点亮屏幕',
      'zh_Hant': '此裝置沒有閃光燈，因此點亮螢幕',
      'zu': 'Le divayisi ayinalo ilambu, ngakho isikrini siyakhanyiswa',
    },
    'q7w3e5r1': {
      'ko': '확인',
      'af': 'Reg so',
      'am': 'እሺ',
      'ar': 'حسنًا',
      'az': 'Tamam',
      'be': 'Добра',
      'bg': 'Добре',
      'bn': 'ঠিক আছে',
      'bs': 'U redu',
      'ca': 'D\'acord',
      'cs': 'OK',
      'da': 'OK',
      'de': 'OK',
      'el': 'Εντάξει',
      'en': 'OK',
      'es': 'Aceptar',
      'et': 'Selge',
      'eu': 'Ados',
      'fa': 'باشه',
      'fi': 'OK',
      'fr': 'D\'accord',
      'gl': 'Aceptar',
      'gu': 'ઠીક છે',
      'he': 'אישור',
      'hi': 'ठीक है',
      'hr': 'U redu',
      'hu': 'Rendben',
      'hy': 'Լավ',
      'id': 'Oke',
      'is': 'Í lagi',
      'it': 'OK',
      'ja': 'OK',
      'ka': 'კარგი',
      'kk': 'Жарайды',
      'km': 'យល់ព្រម',
      'kn': 'ಸರಿ',
      'ky': 'Жарайт',
      'lo': 'ຕົກລົງ',
      'lt': 'Gerai',
      'lv': 'Labi',
      'mk': 'Во ред',
      'ml': 'ശരി',
      'mn': 'Ойлголоо',
      'mr': 'ठीक आहे',
      'ms': 'OK',
      'my': 'ကောင်းပြီ',
      'ne': 'ठीक छ',
      'nl': 'Oké',
      'no': 'OK',
      'or': 'ଠିକ୍ ଅଛି',
      'pa': 'ਠੀਕ ਹੈ',
      'pl': 'OK',
      'ps': 'سمه ده',
      'pt': 'OK',
      'ro': 'OK',
      'ru': 'Понятно',
      'sd': 'ٺيڪ آهي',
      'si': 'හරි',
      'sk': 'OK',
      'sl': 'V redu',
      'sm': 'Ua lelei',
      'sq': 'Në rregull',
      'sr': 'У реду',
      'sv': 'OK',
      'sw': 'Sawa',
      'ta': 'சரி',
      'te': 'సరే',
      'th': 'ตกลง',
      'tl': 'OK',
      'tr': 'Tamam',
      'uk': 'Зрозуміло',
      'ur': 'ٹھیک ہے',
      'uz': 'Tushunarli',
      'vi': 'Đã hiểu',
      'zh_Hans': '知道了',
      'zh_Hant': '知道了',
      'zu': 'Kulungile',
    },
  },
  // Miscellaneous
  {
    'kn3ew2kr': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    't3gwbg8p': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '32zk3bsy': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'fxpycar9': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'zoczg7f5': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '4veq8lhu': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '24jkc6kz': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'ql3mktqp': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'uuuyi67d': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '2j0itvs6': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'm3ckegay': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '03lowxor': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'm6lxdeji': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'bby3aosb': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'sga2c9gb': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'rgxcnjeh': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'ockfij0i': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '82b48a55': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'vydqirqk': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '0e1f0ugr': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'mzhnni6u': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'nkw2ujs4': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'dr2uyv6g': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    '9f6lkupu': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
    'an54bfaa': {
      'ko': '',
      'af': '',
      'am': '',
      'ar': '',
      'az': '',
      'be': '',
      'bg': '',
      'bn': '',
      'bs': '',
      'ca': '',
      'cs': '',
      'da': '',
      'de': '',
      'el': '',
      'en': '',
      'es': '',
      'et': '',
      'eu': '',
      'fa': '',
      'fi': '',
      'fr': '',
      'gl': '',
      'gu': '',
      'he': '',
      'hi': '',
      'hr': '',
      'hu': '',
      'hy': '',
      'id': '',
      'is': '',
      'it': '',
      'ja': '',
      'ka': '',
      'kk': '',
      'km': '',
      'kn': '',
      'ky': '',
      'lo': '',
      'lt': '',
      'lv': '',
      'mk': '',
      'ml': '',
      'mn': '',
      'mr': '',
      'ms': '',
      'my': '',
      'ne': '',
      'nl': '',
      'no': '',
      'or': '',
      'pa': '',
      'pl': '',
      'ps': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'sd': '',
      'si': '',
      'sk': '',
      'sl': '',
      'sm': '',
      'sq': '',
      'sr': '',
      'sv': '',
      'sw': '',
      'ta': '',
      'te': '',
      'th': '',
      'tl': '',
      'tr': '',
      'uk': '',
      'ur': '',
      'uz': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
      'zu': '',
    },
  },
].reduce((a, b) => a..addAll(b));
